In [9]:
import tensorflow as tf 
import numpy as np

In [2]:
x_data = [[1, 2, 1],
          [1, 3, 2],
          [1, 3, 4],
          [1, 5, 5],
          [1, 7, 5],
          [1, 2, 5],
          [1, 6, 6],
          [1, 7, 7]]
y_data = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]

# Evaluation our model using this test dataset
x_test = [[2, 1, 1],
          [3, 1, 2],
          [3, 3, 4]]
y_test = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1]]


In [7]:
learning_rate = 0.1

tf.model = tf.keras.Sequential()
tf.model.add(tf.keras.layers.Dense(units=3, input_dim=3, activation="softmax"))
tf.model.compile(loss='categorical_crossentropy', optimizer = tf.keras.optimizers.SGD(lr=learning_rate), metrics = ['accuracy'])

tf.model.fit(x_data, y_data, epochs=1000)

Epoch 1/1000
1/1 [==============================] - 0s 3ms/step - loss: 3.4868 - accuracy: 0.2500
Epoch 2/1000
1/1 [==============================] - 0s 2ms/step - loss: 2.2756 - accuracy: 0.3750
Epoch 3/1000
1/1 [==============================] - 0s 5ms/step - loss: 1.4183 - accuracy: 0.3750
Epoch 4/1000
1/1 [==============================] - 0s 4ms/step - loss: 1.1681 - accuracy: 0.5000
Epoch 5/1000
1/1 [==============================] - 0s 4ms/step - loss: 1.1034 - accuracy: 0.6250
Epoch 6/1000
1/1 [==============================] - 0s 2ms/step - loss: 1.0846 - accuracy: 0.3750
Epoch 7/1000
1/1 [==============================] - 0s 2ms/step - loss: 1.0691 - accuracy: 0.6250
Epoch 8/1000
1/1 [==============================] - 0s 2ms/step - loss: 1.0553 - accuracy: 0.3750
Epoch 9/1000
1/1 [==============================] - 0s 2ms/step - loss: 1.0425 - accuracy: 0.3750
Epoch 10/1000
1/1 [==============================] - 0s 2ms/step - loss: 1.0303 - accuracy: 0.5000
Epoch 11/1000
1/1 [

1/1 [==============================] - 0s 2ms/step - loss: 0.7137 - accuracy: 0.6250
Epoch 84/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.7121 - accuracy: 0.6250
Epoch 85/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.7104 - accuracy: 0.6250
Epoch 86/1000
1/1 [==============================] - 0s 997us/step - loss: 0.7088 - accuracy: 0.6250
Epoch 87/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.7072 - accuracy: 0.6250
Epoch 88/1000
1/1 [==============================] - 0s 4ms/step - loss: 0.7057 - accuracy: 0.6250
Epoch 89/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.7041 - accuracy: 0.6250
Epoch 90/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.7025 - accuracy: 0.6250
Epoch 91/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.7010 - accuracy: 0.6250
Epoch 92/1000
1/1 [==============================] - 0s 5ms/step - loss: 0.6995 - accuracy: 0.6250
Epoch 93/1000
1/1 [===

1/1 [==============================] - 0s 2ms/step - loss: 0.6199 - accuracy: 0.7500
Epoch 165/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.6191 - accuracy: 0.7500
Epoch 166/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.6183 - accuracy: 0.7500
Epoch 167/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.6174 - accuracy: 0.7500
Epoch 168/1000
1/1 [==============================] - 0s 994us/step - loss: 0.6166 - accuracy: 0.7500
Epoch 169/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.6158 - accuracy: 0.7500
Epoch 170/1000
1/1 [==============================] - 0s 997us/step - loss: 0.6150 - accuracy: 0.7500
Epoch 171/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.6142 - accuracy: 0.7500
Epoch 172/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.6134 - accuracy: 0.7500
Epoch 173/1000
1/1 [==============================] - 0s 997us/step - loss: 0.6126 - accuracy: 0.7500
Epoch 174

1/1 [==============================] - 0s 991us/step - loss: 0.5648 - accuracy: 0.7500
Epoch 246/1000
1/1 [==============================] - 0s 1ms/step - loss: 0.5642 - accuracy: 0.7500
Epoch 247/1000
1/1 [==============================] - 0s 997us/step - loss: 0.5636 - accuracy: 0.7500
Epoch 248/1000
1/1 [==============================] - 0s 996us/step - loss: 0.5631 - accuracy: 0.7500
Epoch 249/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.5625 - accuracy: 0.7500
Epoch 250/1000
1/1 [==============================] - 0s 997us/step - loss: 0.5620 - accuracy: 0.7500
Epoch 251/1000
1/1 [==============================] - 0s 0s/step - loss: 0.5614 - accuracy: 0.7500
Epoch 252/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.5609 - accuracy: 0.7500
Epoch 253/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.5603 - accuracy: 0.7500
Epoch 254/1000
1/1 [==============================] - 0s 1ms/step - loss: 0.5598 - accuracy: 0.7500
Epoch 25

1/1 [==============================] - 0s 997us/step - loss: 0.5252 - accuracy: 0.8750
Epoch 327/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.5248 - accuracy: 0.8750
Epoch 328/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.5243 - accuracy: 0.8750
Epoch 329/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.5239 - accuracy: 0.8750
Epoch 330/1000
1/1 [==============================] - 0s 997us/step - loss: 0.5235 - accuracy: 0.8750
Epoch 331/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.5231 - accuracy: 0.8750
Epoch 332/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.5226 - accuracy: 0.8750
Epoch 333/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.5222 - accuracy: 0.8750
Epoch 334/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.5218 - accuracy: 0.8750
Epoch 335/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.5214 - accuracy: 0.8750
Epoch 336/1

1/1 [==============================] - 0s 2ms/step - loss: 0.4940 - accuracy: 1.0000
Epoch 408/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.4937 - accuracy: 1.0000
Epoch 409/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.4933 - accuracy: 1.0000
Epoch 410/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.4930 - accuracy: 1.0000
Epoch 411/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.4926 - accuracy: 1.0000
Epoch 412/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.4923 - accuracy: 1.0000
Epoch 413/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.4920 - accuracy: 1.0000
Epoch 414/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.4916 - accuracy: 1.0000
Epoch 415/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.4913 - accuracy: 1.0000
Epoch 416/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.4909 - accuracy: 1.0000
Epoch 417/1000


1/1 [==============================] - 0s 2ms/step - loss: 0.4682 - accuracy: 1.0000
Epoch 489/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.4679 - accuracy: 1.0000
Epoch 490/1000
1/1 [==============================] - 0s 997us/step - loss: 0.4676 - accuracy: 1.0000
Epoch 491/1000
1/1 [==============================] - 0s 997us/step - loss: 0.4674 - accuracy: 1.0000
Epoch 492/1000
1/1 [==============================] - 0s 997us/step - loss: 0.4671 - accuracy: 1.0000
Epoch 493/1000
1/1 [==============================] - 0s 996us/step - loss: 0.4668 - accuracy: 1.0000
Epoch 494/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.4665 - accuracy: 1.0000
Epoch 495/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.4662 - accuracy: 1.0000
Epoch 496/1000
1/1 [==============================] - 0s 997us/step - loss: 0.4659 - accuracy: 1.0000
Epoch 497/1000
1/1 [==============================] - 0s 998us/step - loss: 0.4656 - accuracy: 1.0000
Epo

1/1 [==============================] - 0s 1ms/step - loss: 0.4462 - accuracy: 1.0000
Epoch 570/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.4460 - accuracy: 1.0000
Epoch 571/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.4457 - accuracy: 1.0000
Epoch 572/1000
1/1 [==============================] - 0s 998us/step - loss: 0.4455 - accuracy: 1.0000
Epoch 573/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.4452 - accuracy: 1.0000
Epoch 574/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.4450 - accuracy: 1.0000
Epoch 575/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.4447 - accuracy: 1.0000
Epoch 576/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.4445 - accuracy: 1.0000
Epoch 577/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.4442 - accuracy: 1.0000
Epoch 578/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.4440 - accuracy: 1.0000
Epoch 579/100

1/1 [==============================] - 0s 2ms/step - loss: 0.4271 - accuracy: 1.0000
Epoch 651/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.4269 - accuracy: 1.0000
Epoch 652/1000
1/1 [==============================] - 0s 997us/step - loss: 0.4266 - accuracy: 1.0000
Epoch 653/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.4264 - accuracy: 1.0000
Epoch 654/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.4262 - accuracy: 1.0000
Epoch 655/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.4260 - accuracy: 1.0000
Epoch 656/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.4258 - accuracy: 1.0000
Epoch 657/1000
1/1 [==============================] - 0s 997us/step - loss: 0.4255 - accuracy: 1.0000
Epoch 658/1000
1/1 [==============================] - 0s 998us/step - loss: 0.4253 - accuracy: 1.0000
Epoch 659/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.4251 - accuracy: 1.0000
Epoch 660

1/1 [==============================] - 0s 2ms/step - loss: 0.4102 - accuracy: 1.0000
Epoch 732/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.4100 - accuracy: 1.0000
Epoch 733/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.4098 - accuracy: 1.0000
Epoch 734/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.4096 - accuracy: 1.0000
Epoch 735/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.4094 - accuracy: 1.0000
Epoch 736/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.4092 - accuracy: 1.0000
Epoch 737/1000
1/1 [==============================] - 0s 996us/step - loss: 0.4090 - accuracy: 1.0000
Epoch 738/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.4088 - accuracy: 1.0000
Epoch 739/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.4086 - accuracy: 1.0000
Epoch 740/1000
1/1 [==============================] - 0s 996us/step - loss: 0.4084 - accuracy: 1.0000
Epoch 741/1

1/1 [==============================] - 0s 997us/step - loss: 0.3951 - accuracy: 1.0000
Epoch 813/1000
1/1 [==============================] - 0s 997us/step - loss: 0.3949 - accuracy: 1.0000
Epoch 814/1000
1/1 [==============================] - 0s 997us/step - loss: 0.3948 - accuracy: 1.0000
Epoch 815/1000
1/1 [==============================] - 0s 1ms/step - loss: 0.3946 - accuracy: 1.0000
Epoch 816/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.3944 - accuracy: 1.0000
Epoch 817/1000
1/1 [==============================] - 0s 997us/step - loss: 0.3942 - accuracy: 1.0000
Epoch 818/1000
1/1 [==============================] - 0s 996us/step - loss: 0.3941 - accuracy: 1.0000
Epoch 819/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.3939 - accuracy: 1.0000
Epoch 820/1000
1/1 [==============================] - 0s 998us/step - loss: 0.3937 - accuracy: 1.0000
Epoch 821/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.3935 - accuracy: 1.0000
Epo

1/1 [==============================] - 0s 2ms/step - loss: 0.3815 - accuracy: 1.0000
Epoch 894/1000
1/1 [==============================] - 0s 995us/step - loss: 0.3814 - accuracy: 1.0000
Epoch 895/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.3812 - accuracy: 1.0000
Epoch 896/1000
1/1 [==============================] - 0s 997us/step - loss: 0.3811 - accuracy: 1.0000
Epoch 897/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.3809 - accuracy: 1.0000
Epoch 898/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.3807 - accuracy: 1.0000
Epoch 899/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.3806 - accuracy: 1.0000
Epoch 900/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.3804 - accuracy: 1.0000
Epoch 901/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.3803 - accuracy: 1.0000
Epoch 902/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.3801 - accuracy: 1.0000
Epoch 903/1

1/1 [==============================] - 0s 3ms/step - loss: 0.3692 - accuracy: 1.0000
Epoch 975/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.3691 - accuracy: 1.0000
Epoch 976/1000
1/1 [==============================] - 0s 997us/step - loss: 0.3689 - accuracy: 1.0000
Epoch 977/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.3688 - accuracy: 1.0000
Epoch 978/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.3686 - accuracy: 1.0000
Epoch 979/1000
1/1 [==============================] - 0s 997us/step - loss: 0.3685 - accuracy: 1.0000
Epoch 980/1000
1/1 [==============================] - 0s 997us/step - loss: 0.3683 - accuracy: 1.0000
Epoch 981/1000
1/1 [==============================] - 0s 997us/step - loss: 0.3682 - accuracy: 1.0000
Epoch 982/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.3681 - accuracy: 1.0000
Epoch 983/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.3679 - accuracy: 1.0000
Epoch 9

In [6]:
print("Prediction: ", tf.model.predict_classes(x_test))

print("Accuracy: ", tf.model.evaluate(x_test, y_test)[1])

Prediction:  [2 2 2]
1/1 [==============================] - 0s 3ms/step - loss: 6.5547e-04 - accuracy: 1.0000
Accuracy:  1.0


linear regression 적용

In [11]:
# dataset 
xy = np.array([[828.659973, 833.450012, 908100, 828.349976, 831.659973],
               [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
               [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
               [816, 820.958984, 1008100, 815.48999, 819.23999],
               [819.359985, 823, 1188100, 818.469971, 818.97998],
               [819, 823, 1198100, 816, 820.450012],
               [811.700012, 815.25, 1098100, 809.780029, 813.669983],
               [809.51001, 816.659973, 1398100, 804.539978, 809.559998]])
x_data = xy[:,0:-1]
y_data = xy[:,[-1]]

In [12]:
x_data

array([[8.28659973e+02, 8.33450012e+02, 9.08100000e+05, 8.28349976e+02],
       [8.23020020e+02, 8.28070007e+02, 1.82810000e+06, 8.21655029e+02],
       [8.19929993e+02, 8.24400024e+02, 1.43810000e+06, 8.18979980e+02],
       [8.16000000e+02, 8.20958984e+02, 1.00810000e+06, 8.15489990e+02],
       [8.19359985e+02, 8.23000000e+02, 1.18810000e+06, 8.18469971e+02],
       [8.19000000e+02, 8.23000000e+02, 1.19810000e+06, 8.16000000e+02],
       [8.11700012e+02, 8.15250000e+02, 1.09810000e+06, 8.09780029e+02],
       [8.09510010e+02, 8.16659973e+02, 1.39810000e+06, 8.04539978e+02]])

In [13]:
y_data

array([[831.659973],
       [828.070007],
       [824.159973],
       [819.23999 ],
       [818.97998 ],
       [820.450012],
       [813.669983],
       [809.559998]])

In [14]:
tf.model = tf.keras.Sequential()
tf.model.add(tf.keras.layers.Dense(units=1, input_dim=4))
tf.model.add(tf.keras.layers.Activation('linear'))
tf.model.compile(loss='mse', optimizer=tf.keras.optimizers.SGD(lr=1e-5))
tf.model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_2 (Dense)              (None, 1)                 5         
_________________________________________________________________
activation (Activation)      (None, 1)                 0         
Total params: 5
Trainable params: 5
Non-trainable params: 0
_________________________________________________________________


In [15]:
history = tf.model.fit(x_data, y_data, epochs=100)

Epoch 1/100
1/1 [==============================] - 0s 2ms/step - loss: 70082764800.0000
Epoch 2/100
1/1 [==============================] - 0s 2ms/step - loss: 76998351523886228595277824.0000
Epoch 3/100
1/1 [==============================] - 0s 998us/step - loss: inf
Epoch 4/100
1/1 [==============================] - 0s 995us/step - loss: inf
Epoch 5/100
1/1 [==============================] - 0s 2ms/step - loss: inf
Epoch 6/100
1/1 [==============================] - 0s 998us/step - loss: inf
Epoch 7/100
1/1 [==============================] - 0s 2ms/step - loss: nan
Epoch 8/100
1/1 [==============================] - 0s 2ms/step - loss: nan
Epoch 9/100
1/1 [==============================] - 0s 2ms/step - loss: nan
Epoch 10/100
1/1 [==============================] - 0s 3ms/step - loss: nan
Epoch 11/100
1/1 [==============================] - 0s 996us/step - loss: nan
Epoch 12/100
1/1 [==============================] - 0s 2ms/step - loss: nan
Epoch 13/100
1/1 [==============================

데이터의 값의 범위가 너무 커서, loss가 nan 이다. 이럴땐 정규화가 필요하다.

In [17]:
print(history.history['loss'])

[70082764800.0, 7.699835152388623e+25, inf, inf, inf, inf, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]


In [18]:
# 정규화 함수 선언
def min_max_scaler(data):
    numerator = data - np.min(data, 0)
    denumerator = np.max(data, 0) - np.min(data, 0)
    
    return numerator/(denumerator + 1e-7)

In [19]:
# data 정규화
xy = min_max_scaler(xy)
print(xy)

[[0.99999999 0.99999999 0.         1.         1.        ]
 [0.70548491 0.70439552 1.         0.71881782 0.83755791]
 [0.54412549 0.50274824 0.57608696 0.606468   0.6606331 ]
 [0.33890353 0.31368023 0.10869565 0.45989134 0.43800918]
 [0.51436    0.42582389 0.30434783 0.58504805 0.42624401]
 [0.49556179 0.42582389 0.31521739 0.48131134 0.49276137]
 [0.11436064 0.         0.20652174 0.22007776 0.18597238]
 [0.         0.07747099 0.5326087  0.         0.        ]]


In [20]:
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

tf.model = tf.keras.Sequential()
tf.model.add(tf.keras.layers.Dense(units=1, input_dim= 4))
tf.model.add(tf.keras.layers.Activation('linear'))
tf.model.compile(loss='mse', optimizer=tf.keras.optimizers.SGD(lr=1e-5))
tf.model.summary()

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_3 (Dense)              (None, 1)                 5         
_________________________________________________________________
activation_1 (Activation)    (None, 1)                 0         
Total params: 5
Trainable params: 5
Non-trainable params: 0
_________________________________________________________________


In [21]:
history = tf.model.fit(x_data, y_data, epochs=1000)

Epoch 1/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.3428
Epoch 2/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.3428
Epoch 3/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.3428
Epoch 4/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.3427
Epoch 5/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.3427
Epoch 6/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.3427
Epoch 7/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.3427
Epoch 8/1000
1/1 [==============================] - 0s 998us/step - loss: 0.3427
Epoch 9/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.3426
Epoch 10/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.3426
Epoch 11/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.3426
Epoch 12/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.3426
Epoch 13/1000
1/1 [============================

1/1 [==============================] - 0s 998us/step - loss: 0.3408
Epoch 103/1000
1/1 [==============================] - 0s 1ms/step - loss: 0.3408
Epoch 104/1000
1/1 [==============================] - 0s 0s/step - loss: 0.3408
Epoch 105/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.3407
Epoch 106/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.3407
Epoch 107/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.3407
Epoch 108/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.3407
Epoch 109/1000
1/1 [==============================] - 0s 1ms/step - loss: 0.3407
Epoch 110/1000
1/1 [==============================] - 0s 1ms/step - loss: 0.3406
Epoch 111/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.3406
Epoch 112/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.3406
Epoch 113/1000
1/1 [==============================] - 0s 997us/step - loss: 0.3406
Epoch 114/1000
1/1 [====================

1/1 [==============================] - 0s 996us/step - loss: 0.3388
Epoch 203/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.3388
Epoch 204/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.3388
Epoch 205/1000
1/1 [==============================] - 0s 991us/step - loss: 0.3388
Epoch 206/1000
1/1 [==============================] - 0s 1ms/step - loss: 0.3388
Epoch 207/1000
1/1 [==============================] - 0s 996us/step - loss: 0.3387
Epoch 208/1000
1/1 [==============================] - 0s 999us/step - loss: 0.3387
Epoch 209/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.3387
Epoch 210/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.3387
Epoch 211/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.3387
Epoch 212/1000
1/1 [==============================] - 0s 997us/step - loss: 0.3386
Epoch 213/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.3386
Epoch 214/1000
1/1 [=============

1/1 [==============================] - 0s 5ms/step - loss: 0.3369
Epoch 303/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.3369
Epoch 304/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.3368
Epoch 305/1000
1/1 [==============================] - 0s 4ms/step - loss: 0.3368
Epoch 306/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.3368
Epoch 307/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.3368
Epoch 308/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.3368
Epoch 309/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.3367
Epoch 310/1000
1/1 [==============================] - 0s 998us/step - loss: 0.3367
Epoch 311/1000
1/1 [==============================] - 0s 6ms/step - loss: 0.3367
Epoch 312/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.3367
Epoch 313/1000
1/1 [==============================] - 0s 7ms/step - loss: 0.3367
Epoch 314/1000
1/1 [=====================

1/1 [==============================] - 0s 996us/step - loss: 0.3349
Epoch 403/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.3349
Epoch 404/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.3349
Epoch 405/1000
1/1 [==============================] - 0s 997us/step - loss: 0.3349
Epoch 406/1000
1/1 [==============================] - 0s 997us/step - loss: 0.3349
Epoch 407/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.3349
Epoch 408/1000
1/1 [==============================] - 0s 991us/step - loss: 0.3348
Epoch 409/1000
1/1 [==============================] - 0s 997us/step - loss: 0.3348
Epoch 410/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.3348
Epoch 411/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.3348
Epoch 412/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.3348
Epoch 413/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.3347
Epoch 414/1000
1/1 [=============

Epoch 502/1000
1/1 [==============================] - 0s 998us/step - loss: 0.3330
Epoch 503/1000
1/1 [==============================] - 0s 998us/step - loss: 0.3330
Epoch 504/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.3330
Epoch 505/1000
1/1 [==============================] - 0s 997us/step - loss: 0.3330
Epoch 506/1000
1/1 [==============================] - 0s 0s/step - loss: 0.3329
Epoch 507/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.3329
Epoch 508/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.3329
Epoch 509/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.3329
Epoch 510/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.3329
Epoch 511/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.3329
Epoch 512/1000
1/1 [==============================] - 0s 999us/step - loss: 0.3328
Epoch 513/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.3328
Epoch 514/1000
1/1 [=

1/1 [==============================] - 0s 997us/step - loss: 0.3311
Epoch 602/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.3311
Epoch 603/1000
1/1 [==============================] - 0s 993us/step - loss: 0.3311
Epoch 604/1000
1/1 [==============================] - 0s 997us/step - loss: 0.3311
Epoch 605/1000
1/1 [==============================] - 0s 996us/step - loss: 0.3311
Epoch 606/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.3310
Epoch 607/1000
1/1 [==============================] - 0s 997us/step - loss: 0.3310
Epoch 608/1000
1/1 [==============================] - 0s 0s/step - loss: 0.3310
Epoch 609/1000
1/1 [==============================] - 0s 998us/step - loss: 0.3310
Epoch 610/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.3310
Epoch 611/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.3309
Epoch 612/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.3309
Epoch 613/1000
1/1 [============

1/1 [==============================] - 0s 3ms/step - loss: 0.3292
Epoch 702/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.3292
Epoch 703/1000
1/1 [==============================] - 0s 997us/step - loss: 0.3292
Epoch 704/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.3292
Epoch 705/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.3292
Epoch 706/1000
1/1 [==============================] - 0s 998us/step - loss: 0.3292
Epoch 707/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.3291
Epoch 708/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.3291
Epoch 709/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.3291
Epoch 710/1000
1/1 [==============================] - 0s 997us/step - loss: 0.3291
Epoch 711/1000
1/1 [==============================] - 0s 998us/step - loss: 0.3291
Epoch 712/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.3290
Epoch 713/1000
1/1 [===============

1/1 [==============================] - 0s 3ms/step - loss: 0.3274
Epoch 802/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.3273
Epoch 803/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.3273
Epoch 804/1000
1/1 [==============================] - 0s 997us/step - loss: 0.3273
Epoch 805/1000
1/1 [==============================] - 0s 998us/step - loss: 0.3273
Epoch 806/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.3273
Epoch 807/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.3273
Epoch 808/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.3272
Epoch 809/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.3272
Epoch 810/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.3272
Epoch 811/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.3272
Epoch 812/1000
1/1 [==============================] - 0s 997us/step - loss: 0.3272
Epoch 813/1000
1/1 [=================

1/1 [==============================] - 0s 998us/step - loss: 0.3255
Epoch 901/1000
1/1 [==============================] - 0s 998us/step - loss: 0.3255
Epoch 902/1000
1/1 [==============================] - 0s 997us/step - loss: 0.3255
Epoch 903/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.3255
Epoch 904/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.3254
Epoch 905/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.3254
Epoch 906/1000
1/1 [==============================] - 0s 997us/step - loss: 0.3254
Epoch 907/1000
1/1 [==============================] - 0s 997us/step - loss: 0.3254
Epoch 908/1000
1/1 [==============================] - 0s 997us/step - loss: 0.3254
Epoch 909/1000
1/1 [==============================] - 0s 998us/step - loss: 0.3254
Epoch 910/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.3253
Epoch 911/1000
1/1 [==============================] - 0s 998us/step - loss: 0.3253
Epoch 912/1000
1/1 [=======

1/1 [==============================] - 0s 4ms/step - loss: 0.3237


In [23]:
predictions = tf.model.predict(x_data)
score = tf.model.evaluate(x_data, y_data)

1/1 [==============================] - 0s 3ms/step - loss: 0.3237


In [24]:
print('Prediction: ', predictions)
print('Cost: ', score)

Prediction:  [[ 0.9008025 ]
 [-0.31735995]
 [-0.0960405 ]
 [ 0.18435474]
 [ 0.08979632]
 [ 0.08031232]
 [-0.1985967 ]
 [-0.42124674]]
Cost:  0.32365304231643677
