In [31]:
import tensorflow as tf
import numpy as np

In [32]:
# sampledata 구축
x_raw = [[1, 2, 1, 1],
          [2, 1, 3, 2],
          [3, 1, 3, 4],
          [4, 1, 5, 5],
          [1, 7, 5, 5],
          [1, 2, 5, 6],
          [1, 6, 6, 6],
          [1, 7, 7, 7]]
y_raw = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]

In [33]:
x_data = np.array(x_raw, dtype=np.float32)
y_data = np.array(y_raw, dtype=np.float32)

n_classes = 3

tf.model = tf.keras.Sequential()
tf.model.add(tf.keras.layers.Dense(input_dim = 4, units=n_classes, use_bias = True)) # use_bias가 true이면 기본값을 사용한다.
tf.model.add(tf.keras.layers.Activation('softmax'))

tf.model.compile(loss='categorical_crossentropy', optimizer=tf.keras.optimizers.SGD(lr=0.1), metrics=['accuracy'])
tf.model.summary()

Model: "sequential_12"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_6 (Dense)              (None, 3)                 15        
_________________________________________________________________
activation_3 (Activation)    (None, 3)                 0         
Total params: 15
Trainable params: 15
Non-trainable params: 0
_________________________________________________________________


In [34]:
history = tf.model.fit(x_data, y_data, epochs=2000)

Epoch 1/2000
1/1 [==============================] - 0s 2ms/step - loss: 4.5612 - accuracy: 0.3750
Epoch 2/2000
1/1 [==============================] - 0s 2ms/step - loss: 2.8582 - accuracy: 0.2500
Epoch 3/2000
1/1 [==============================] - 0s 2ms/step - loss: 2.2210 - accuracy: 0.1250
Epoch 4/2000
1/1 [==============================] - 0s 1ms/step - loss: 1.9049 - accuracy: 0.1250
Epoch 5/2000
1/1 [==============================] - 0s 2ms/step - loss: 1.7293 - accuracy: 0.2500
Epoch 6/2000
1/1 [==============================] - 0s 997us/step - loss: 1.5760 - accuracy: 0.2500
Epoch 7/2000
1/1 [==============================] - 0s 2ms/step - loss: 1.4458 - accuracy: 0.2500
Epoch 8/2000
1/1 [==============================] - 0s 2ms/step - loss: 1.3379 - accuracy: 0.3750
Epoch 9/2000
1/1 [==============================] - 0s 1ms/step - loss: 1.2597 - accuracy: 0.2500
Epoch 10/2000
1/1 [==============================] - 0s 997us/step - loss: 1.2110 - accuracy: 0.3750
Epoch 11/2000
1

1/1 [==============================] - 0s 995us/step - loss: 0.7129 - accuracy: 0.7500
Epoch 83/2000
1/1 [==============================] - 0s 997us/step - loss: 0.6618 - accuracy: 0.6250
Epoch 84/2000
1/1 [==============================] - 0s 998us/step - loss: 0.7092 - accuracy: 0.7500
Epoch 85/2000
1/1 [==============================] - 0s 0s/step - loss: 0.6579 - accuracy: 0.6250
Epoch 86/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.7055 - accuracy: 0.7500
Epoch 87/2000
1/1 [==============================] - 0s 973us/step - loss: 0.6542 - accuracy: 0.6250
Epoch 88/2000
1/1 [==============================] - 0s 997us/step - loss: 0.7020 - accuracy: 0.7500
Epoch 89/2000
1/1 [==============================] - 0s 996us/step - loss: 0.6505 - accuracy: 0.6250
Epoch 90/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.6986 - accuracy: 0.7500
Epoch 91/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.6470 - accuracy: 0.6250
Epoch 92/2000

1/1 [==============================] - 0s 998us/step - loss: 0.6183 - accuracy: 0.7500
Epoch 163/2000
1/1 [==============================] - 0s 998us/step - loss: 0.5633 - accuracy: 0.7500
Epoch 164/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.6166 - accuracy: 0.7500
Epoch 165/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.5617 - accuracy: 0.7500
Epoch 166/2000
1/1 [==============================] - 0s 997us/step - loss: 0.6150 - accuracy: 0.7500
Epoch 167/2000
1/1 [==============================] - 0s 998us/step - loss: 0.5601 - accuracy: 0.7500
Epoch 168/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.6134 - accuracy: 0.7500
Epoch 169/2000
1/1 [==============================] - 0s 3ms/step - loss: 0.5585 - accuracy: 0.7500
Epoch 170/2000
1/1 [==============================] - 0s 3ms/step - loss: 0.6118 - accuracy: 0.7500
Epoch 171/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.5569 - accuracy: 0.7500
Epoch 1

1/1 [==============================] - 0s 3ms/step - loss: 0.5093 - accuracy: 0.7500
Epoch 244/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.5616 - accuracy: 0.7500
Epoch 245/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.5082 - accuracy: 0.7500
Epoch 246/2000
1/1 [==============================] - 0s 3ms/step - loss: 0.5604 - accuracy: 0.7500
Epoch 247/2000
1/1 [==============================] - 0s 998us/step - loss: 0.5071 - accuracy: 0.7500
Epoch 248/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.5592 - accuracy: 0.7500
Epoch 249/2000
1/1 [==============================] - 0s 997us/step - loss: 0.5059 - accuracy: 0.7500
Epoch 250/2000
1/1 [==============================] - 0s 3ms/step - loss: 0.5580 - accuracy: 0.7500
Epoch 251/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.5048 - accuracy: 0.7500
Epoch 252/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.5568 - accuracy: 0.7500
Epoch 253/2

1/1 [==============================] - 0s 1ms/step - loss: 0.5166 - accuracy: 0.8750
Epoch 325/2000
1/1 [==============================] - 0s 5ms/step - loss: 0.4677 - accuracy: 0.7500
Epoch 326/2000
1/1 [==============================] - 0s 997us/step - loss: 0.5155 - accuracy: 0.8750
Epoch 327/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.4668 - accuracy: 0.7500
Epoch 328/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.5144 - accuracy: 0.8750
Epoch 329/2000
1/1 [==============================] - 0s 998us/step - loss: 0.4659 - accuracy: 0.7500
Epoch 330/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.5134 - accuracy: 0.8750
Epoch 331/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.4650 - accuracy: 0.7500
Epoch 332/2000
1/1 [==============================] - 0s 4ms/step - loss: 0.5123 - accuracy: 0.8750
Epoch 333/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.4641 - accuracy: 0.7500
Epoch 334/2

1/1 [==============================] - 0s 2ms/step - loss: 0.4331 - accuracy: 0.7500
Epoch 406/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.4746 - accuracy: 0.8750
Epoch 407/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.4323 - accuracy: 0.7500
Epoch 408/2000
1/1 [==============================] - 0s 997us/step - loss: 0.4736 - accuracy: 0.8750
Epoch 409/2000
1/1 [==============================] - 0s 997us/step - loss: 0.4315 - accuracy: 0.7500
Epoch 410/2000
1/1 [==============================] - 0s 996us/step - loss: 0.4726 - accuracy: 0.8750
Epoch 411/2000
1/1 [==============================] - 0s 998us/step - loss: 0.4307 - accuracy: 0.7500
Epoch 412/2000
1/1 [==============================] - 0s 5ms/step - loss: 0.4716 - accuracy: 0.8750
Epoch 413/2000
1/1 [==============================] - 0s 3ms/step - loss: 0.4299 - accuracy: 0.7500
Epoch 414/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.4706 - accuracy: 0.8750
Epoch 4

1/1 [==============================] - 0s 2ms/step - loss: 0.4356 - accuracy: 0.8750
Epoch 487/2000
1/1 [==============================] - 0s 998us/step - loss: 0.4008 - accuracy: 0.7500
Epoch 488/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.4346 - accuracy: 0.8750
Epoch 489/2000
1/1 [==============================] - 0s 997us/step - loss: 0.4000 - accuracy: 0.7500
Epoch 490/2000
1/1 [==============================] - 0s 0s/step - loss: 0.4337 - accuracy: 0.8750
Epoch 491/2000
1/1 [==============================] - 0s 1000us/step - loss: 0.3992 - accuracy: 0.7500
Epoch 492/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.4327 - accuracy: 0.8750
Epoch 493/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.3985 - accuracy: 0.7500
Epoch 494/2000
1/1 [==============================] - 0s 1000us/step - loss: 0.4318 - accuracy: 0.8750
Epoch 495/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.3977 - accuracy: 0.7500
Epoch 

1/1 [==============================] - 0s 2ms/step - loss: 0.3708 - accuracy: 0.8750
Epoch 568/2000
1/1 [==============================] - 0s 998us/step - loss: 0.3966 - accuracy: 0.8750
Epoch 569/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.3700 - accuracy: 0.8750
Epoch 570/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.3957 - accuracy: 0.8750
Epoch 571/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.3693 - accuracy: 0.8750
Epoch 572/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.3947 - accuracy: 0.8750
Epoch 573/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.3685 - accuracy: 0.8750
Epoch 574/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.3938 - accuracy: 0.8750
Epoch 575/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.3678 - accuracy: 0.8750
Epoch 576/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.3929 - accuracy: 0.8750
Epoch 577/200

1/1 [==============================] - 0s 1ms/step - loss: 0.3591 - accuracy: 0.8750
Epoch 649/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.3406 - accuracy: 0.8750
Epoch 650/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.3582 - accuracy: 0.8750
Epoch 651/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.3399 - accuracy: 0.8750
Epoch 652/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.3572 - accuracy: 0.8750
Epoch 653/2000
1/1 [==============================] - 0s 998us/step - loss: 0.3392 - accuracy: 0.8750
Epoch 654/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.3563 - accuracy: 0.8750
Epoch 655/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.3384 - accuracy: 0.8750
Epoch 656/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.3554 - accuracy: 0.8750
Epoch 657/2000
1/1 [==============================] - 0s 997us/step - loss: 0.3377 - accuracy: 0.8750
Epoch 658/2

1/1 [==============================] - 0s 2ms/step - loss: 0.3111 - accuracy: 0.8750
Epoch 730/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.3211 - accuracy: 0.8750
Epoch 731/2000
1/1 [==============================] - 0s 998us/step - loss: 0.3104 - accuracy: 0.8750
Epoch 732/2000
1/1 [==============================] - 0s 3ms/step - loss: 0.3201 - accuracy: 0.8750
Epoch 733/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.3096 - accuracy: 0.8750
Epoch 734/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.3192 - accuracy: 0.8750
Epoch 735/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.3089 - accuracy: 0.8750
Epoch 736/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.3183 - accuracy: 0.8750
Epoch 737/2000
1/1 [==============================] - 0s 998us/step - loss: 0.3082 - accuracy: 0.8750
Epoch 738/2000
1/1 [==============================] - 0s 996us/step - loss: 0.3174 - accuracy: 0.8750
Epoch 739

1/1 [==============================] - 0s 2ms/step - loss: 0.2814 - accuracy: 1.0000
Epoch 810/2000
1/1 [==============================] - 0s 997us/step - loss: 0.2850 - accuracy: 0.8750
Epoch 811/2000
1/1 [==============================] - 0s 997us/step - loss: 0.2806 - accuracy: 1.0000
Epoch 812/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.2841 - accuracy: 0.8750
Epoch 813/2000
1/1 [==============================] - 0s 998us/step - loss: 0.2799 - accuracy: 1.0000
Epoch 814/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.2832 - accuracy: 0.8750
Epoch 815/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.2792 - accuracy: 1.0000
Epoch 816/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.2824 - accuracy: 0.8750
Epoch 817/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.2784 - accuracy: 1.0000
Epoch 818/2000
1/1 [==============================] - 0s 998us/step - loss: 0.2815 - accuracy: 0.8750
Epoch 8

1/1 [==============================] - 0s 2ms/step - loss: 0.2540 - accuracy: 1.0000
Epoch 891/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.2533 - accuracy: 1.0000
Epoch 892/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.2534 - accuracy: 1.0000
Epoch 893/2000
1/1 [==============================] - 0s 996us/step - loss: 0.2527 - accuracy: 1.0000
Epoch 894/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.2528 - accuracy: 1.0000
Epoch 895/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.2522 - accuracy: 1.0000
Epoch 896/2000
1/1 [==============================] - 0s 997us/step - loss: 0.2522 - accuracy: 1.0000
Epoch 897/2000
1/1 [==============================] - 0s 997us/step - loss: 0.2516 - accuracy: 1.0000
Epoch 898/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.2516 - accuracy: 1.0000
Epoch 899/2000
1/1 [==============================] - 0s 996us/step - loss: 0.2511 - accuracy: 1.0000
Epoch 9

1/1 [==============================] - 0s 998us/step - loss: 0.2382 - accuracy: 1.0000
Epoch 972/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.2380 - accuracy: 1.0000
Epoch 973/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.2379 - accuracy: 1.0000
Epoch 974/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.2378 - accuracy: 1.0000
Epoch 975/2000
1/1 [==============================] - 0s 8ms/step - loss: 0.2377 - accuracy: 1.0000
Epoch 976/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.2375 - accuracy: 1.0000
Epoch 977/2000
1/1 [==============================] - 0s 997us/step - loss: 0.2374 - accuracy: 1.0000
Epoch 978/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.2373 - accuracy: 1.0000
Epoch 979/2000
1/1 [==============================] - 0s 998us/step - loss: 0.2372 - accuracy: 1.0000
Epoch 980/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.2370 - accuracy: 1.0000
Epoch 981

1/1 [==============================] - 0s 2ms/step - loss: 0.2285 - accuracy: 1.0000
Epoch 1052/2000
1/1 [==============================] - 0s 997us/step - loss: 0.2284 - accuracy: 1.0000
Epoch 1053/2000
1/1 [==============================] - 0s 998us/step - loss: 0.2283 - accuracy: 1.0000
Epoch 1054/2000
1/1 [==============================] - 0s 3ms/step - loss: 0.2281 - accuracy: 1.0000
Epoch 1055/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.2280 - accuracy: 1.0000
Epoch 1056/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.2279 - accuracy: 1.0000
Epoch 1057/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.2278 - accuracy: 1.0000
Epoch 1058/2000
1/1 [==============================] - 0s 998us/step - loss: 0.2277 - accuracy: 1.0000
Epoch 1059/2000
1/1 [==============================] - 0s 998us/step - loss: 0.2276 - accuracy: 1.0000
Epoch 1060/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.2274 - accuracy: 1.000

1/1 [==============================] - 0s 992us/step - loss: 0.2196 - accuracy: 1.0000
Epoch 1132/2000
1/1 [==============================] - 0s 997us/step - loss: 0.2195 - accuracy: 1.0000
Epoch 1133/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.2193 - accuracy: 1.0000
Epoch 1134/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.2192 - accuracy: 1.0000
Epoch 1135/2000
1/1 [==============================] - 0s 997us/step - loss: 0.2191 - accuracy: 1.0000
Epoch 1136/2000
1/1 [==============================] - 0s 997us/step - loss: 0.2190 - accuracy: 1.0000
Epoch 1137/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.2189 - accuracy: 1.0000
Epoch 1138/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.2188 - accuracy: 1.0000
Epoch 1139/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.2187 - accuracy: 1.0000
Epoch 1140/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.2186 - accuracy: 1.000

1/1 [==============================] - 0s 2ms/step - loss: 0.2113 - accuracy: 1.0000
Epoch 1212/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.2112 - accuracy: 1.0000
Epoch 1213/2000
1/1 [==============================] - 0s 998us/step - loss: 0.2111 - accuracy: 1.0000
Epoch 1214/2000
1/1 [==============================] - 0s 997us/step - loss: 0.2110 - accuracy: 1.0000
Epoch 1215/2000
1/1 [==============================] - 0s 997us/step - loss: 0.2109 - accuracy: 1.0000
Epoch 1216/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.2108 - accuracy: 1.0000
Epoch 1217/2000
1/1 [==============================] - 0s 998us/step - loss: 0.2107 - accuracy: 1.0000
Epoch 1218/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.2106 - accuracy: 1.0000
Epoch 1219/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.2105 - accuracy: 1.0000
Epoch 1220/2000
1/1 [==============================] - 0s 997us/step - loss: 0.2104 - accuracy: 1.0

1/1 [==============================] - 0s 998us/step - loss: 0.2037 - accuracy: 1.0000
Epoch 1291/2000
1/1 [==============================] - 0s 998us/step - loss: 0.2036 - accuracy: 1.0000
Epoch 1292/2000
1/1 [==============================] - 0s 996us/step - loss: 0.2035 - accuracy: 1.0000
Epoch 1293/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.2034 - accuracy: 1.0000
Epoch 1294/2000
1/1 [==============================] - 0s 998us/step - loss: 0.2033 - accuracy: 1.0000
Epoch 1295/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.2033 - accuracy: 1.0000
Epoch 1296/2000
1/1 [==============================] - 0s 977us/step - loss: 0.2032 - accuracy: 1.0000
Epoch 1297/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.2031 - accuracy: 1.0000
Epoch 1298/2000
1/1 [==============================] - 0s 997us/step - loss: 0.2030 - accuracy: 1.0000
Epoch 1299/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.2029 - accuracy: 1

1/1 [==============================] - 0s 998us/step - loss: 0.1966 - accuracy: 1.0000
Epoch 1370/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.1966 - accuracy: 1.0000
Epoch 1371/2000
1/1 [==============================] - 0s 997us/step - loss: 0.1965 - accuracy: 1.0000
Epoch 1372/2000
1/1 [==============================] - 0s 998us/step - loss: 0.1964 - accuracy: 1.0000
Epoch 1373/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.1963 - accuracy: 1.0000
Epoch 1374/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.1962 - accuracy: 1.0000
Epoch 1375/2000
1/1 [==============================] - 0s 999us/step - loss: 0.1961 - accuracy: 1.0000
Epoch 1376/2000
1/1 [==============================] - 0s 997us/step - loss: 0.1960 - accuracy: 1.0000
Epoch 1377/2000
1/1 [==============================] - 0s 991us/step - loss: 0.1960 - accuracy: 1.0000
Epoch 1378/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.1959 - accuracy: 1

1/1 [==============================] - 0s 1ms/step - loss: 0.1900 - accuracy: 1.0000
Epoch 1450/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.1899 - accuracy: 1.0000
Epoch 1451/2000
1/1 [==============================] - 0s 998us/step - loss: 0.1898 - accuracy: 1.0000
Epoch 1452/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.1897 - accuracy: 1.0000
Epoch 1453/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.1896 - accuracy: 1.0000
Epoch 1454/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.1895 - accuracy: 1.0000
Epoch 1455/2000
1/1 [==============================] - 0s 5ms/step - loss: 0.1895 - accuracy: 1.0000
Epoch 1456/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.1894 - accuracy: 1.0000
Epoch 1457/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.1893 - accuracy: 1.0000
Epoch 1458/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.1892 - accuracy: 1.0000
Epoc

1/1 [==============================] - 0s 997us/step - loss: 0.1837 - accuracy: 1.0000
Epoch 1530/2000
1/1 [==============================] - 0s 997us/step - loss: 0.1836 - accuracy: 1.0000
Epoch 1531/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.1835 - accuracy: 1.0000
Epoch 1532/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.1835 - accuracy: 1.0000
Epoch 1533/2000
1/1 [==============================] - 0s 998us/step - loss: 0.1834 - accuracy: 1.0000
Epoch 1534/2000
1/1 [==============================] - 0s 998us/step - loss: 0.1833 - accuracy: 1.0000
Epoch 1535/2000
1/1 [==============================] - 0s 997us/step - loss: 0.1832 - accuracy: 1.0000
Epoch 1536/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.1832 - accuracy: 1.0000
Epoch 1537/2000
1/1 [==============================] - 0s 998us/step - loss: 0.1831 - accuracy: 1.0000
Epoch 1538/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.1830 - accuracy: 1

1/1 [==============================] - 0s 2ms/step - loss: 0.1778 - accuracy: 1.0000
Epoch 1610/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.1777 - accuracy: 1.0000
Epoch 1611/2000
1/1 [==============================] - 0s 998us/step - loss: 0.1777 - accuracy: 1.0000
Epoch 1612/2000
1/1 [==============================] - 0s 997us/step - loss: 0.1776 - accuracy: 1.0000
Epoch 1613/2000
1/1 [==============================] - 0s 997us/step - loss: 0.1775 - accuracy: 1.0000
Epoch 1614/2000
1/1 [==============================] - 0s 998us/step - loss: 0.1775 - accuracy: 1.0000
Epoch 1615/2000
1/1 [==============================] - 0s 997us/step - loss: 0.1774 - accuracy: 1.0000
Epoch 1616/2000
1/1 [==============================] - 0s 997us/step - loss: 0.1773 - accuracy: 1.0000
Epoch 1617/2000
1/1 [==============================] - 0s 997us/step - loss: 0.1772 - accuracy: 1.0000
Epoch 1618/2000
1/1 [==============================] - 0s 997us/step - loss: 0.1772 - accurac

1/1 [==============================] - 0s 996us/step - loss: 0.1723 - accuracy: 1.0000
Epoch 1690/2000
1/1 [==============================] - 0s 998us/step - loss: 0.1722 - accuracy: 1.0000
Epoch 1691/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.1721 - accuracy: 1.0000
Epoch 1692/2000
1/1 [==============================] - ETA: 0s - loss: 0.1721 - accuracy: 1.00 - 0s 2ms/step - loss: 0.1721 - accuracy: 1.0000
Epoch 1693/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.1720 - accuracy: 1.0000
Epoch 1694/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.1719 - accuracy: 1.0000
Epoch 1695/2000
1/1 [==============================] - 0s 3ms/step - loss: 0.1719 - accuracy: 1.0000
Epoch 1696/2000
1/1 [==============================] - 0s 4ms/step - loss: 0.1718 - accuracy: 1.0000
Epoch 1697/2000
1/1 [==============================] - 0s 998us/step - loss: 0.1717 - accuracy: 1.0000
Epoch 1698/2000
1/1 [==============================] - 0s 2

1/1 [==============================] - 0s 997us/step - loss: 0.1671 - accuracy: 1.0000
Epoch 1770/2000
1/1 [==============================] - 0s 997us/step - loss: 0.1670 - accuracy: 1.0000
Epoch 1771/2000
1/1 [==============================] - 0s 997us/step - loss: 0.1670 - accuracy: 1.0000
Epoch 1772/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.1669 - accuracy: 1.0000
Epoch 1773/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.1668 - accuracy: 1.0000
Epoch 1774/2000
1/1 [==============================] - 0s 997us/step - loss: 0.1668 - accuracy: 1.0000
Epoch 1775/2000
1/1 [==============================] - 0s 3ms/step - loss: 0.1667 - accuracy: 1.0000
Epoch 1776/2000
1/1 [==============================] - 0s 997us/step - loss: 0.1666 - accuracy: 1.0000
Epoch 1777/2000
1/1 [==============================] - 0s 997us/step - loss: 0.1666 - accuracy: 1.0000
Epoch 1778/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.1665 - accuracy: 1

1/1 [==============================] - 0s 2ms/step - loss: 0.1622 - accuracy: 1.0000
Epoch 1850/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.1621 - accuracy: 1.0000
Epoch 1851/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.1621 - accuracy: 1.0000
Epoch 1852/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.1620 - accuracy: 1.0000
Epoch 1853/2000
1/1 [==============================] - 0s 997us/step - loss: 0.1619 - accuracy: 1.0000
Epoch 1854/2000
1/1 [==============================] - 0s 997us/step - loss: 0.1619 - accuracy: 1.0000
Epoch 1855/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.1618 - accuracy: 1.0000
Epoch 1856/2000
1/1 [==============================] - 0s 1000us/step - loss: 0.1618 - accuracy: 1.0000
Epoch 1857/2000
1/1 [==============================] - 0s 997us/step - loss: 0.1617 - accuracy: 1.0000
Epoch 1858/2000
1/1 [==============================] - 0s 7ms/step - loss: 0.1616 - accuracy: 1.00

1/1 [==============================] - 0s 995us/step - loss: 0.1575 - accuracy: 1.0000
Epoch 1930/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.1575 - accuracy: 1.0000
Epoch 1931/2000
1/1 [==============================] - 0s 997us/step - loss: 0.1574 - accuracy: 1.0000
Epoch 1932/2000
1/1 [==============================] - 0s 3ms/step - loss: 0.1574 - accuracy: 1.0000
Epoch 1933/2000
1/1 [==============================] - 0s 998us/step - loss: 0.1573 - accuracy: 1.0000
Epoch 1934/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.1573 - accuracy: 1.0000
Epoch 1935/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.1572 - accuracy: 1.0000
Epoch 1936/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.1571 - accuracy: 1.0000
Epoch 1937/2000
1/1 [==============================] - 0s 991us/step - loss: 0.1571 - accuracy: 1.0000
Epoch 1938/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.1570 - accuracy: 1.000

In [35]:
print('--------------')
a = tf.model.predict(np.array([[1,11,7,9]]))
print(a, tf.keras.backend.eval(tf.argmax(a,axis=1)))

print('--------------')
b = tf.model.predict(np.array([[1,3,4,3]]))
print(b, tf.keras.backend.eval(tf.argmax(b,axis=1)))

print('--------------')
c = tf.model.predict(np.array([[1,1,0,1]]))
print(c, tf.keras.backend.eval(tf.argmax(c,axis=1)))

print('--------------')
all = tf.model.predict(np.array([[1,11,7,9], [1,3,4,3], [1,1,0,1]]))
all_onehot = tf.model.predict_classes(np.array([[1,11,7,9], [1,3,4,3], [1,1,0,1]]))
print(all, all_onehot)

--------------
[[4.0837862e-03 9.9590635e-01 9.8461196e-06]] [1]
--------------
[[0.8729186  0.11378787 0.01329351]] [0]
--------------
[[1.19867885e-08 3.42107640e-04 9.99657869e-01]] [2]
--------------
[[4.08379361e-03 9.95906353e-01 9.84612871e-06]
 [8.72918487e-01 1.13787934e-01 1.32935261e-02]
 [1.19867654e-08 3.42107640e-04 9.99657869e-01]] [1 0 2]


직접 데이터 가져와서 적용해보기 

In [36]:
xy = np.loadtxt('../../../DeepLearningZeroToAll/DeepLearningZeroToAll-master/data-04-zoo.csv', delimiter=',', dtype = np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

print(x_data.shape, y_data.shape)

nb_classes = 7

y_one_hot = tf.keras.utils.to_categorical(y_data, nb_classes)
print("one_hot:", y_one_hot)


(101, 16) (101, 1)
one_hot: [[1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0

In [37]:
tf.model = tf.keras.Sequential()
tf.model.add(tf.keras.layers.Dense(units=nb_classes, input_dim=16, activation='softmax'))
tf.model.compile(loss='categorical_crossentropy', optimizer = tf.keras.optimizers.SGD(lr=0.1), metrics=['accuracy'])
tf.model.summary()

Model: "sequential_13"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_7 (Dense)              (None, 7)                 119       
Total params: 119
Trainable params: 119
Non-trainable params: 0
_________________________________________________________________


In [38]:
history = tf.model.fit(x_data, y_one_hot, epochs=1000)

Epoch 1/1000
4/4 [==============================] - 0s 1ms/step - loss: 2.0873 - accuracy: 0.2772
Epoch 2/1000
4/4 [==============================] - 0s 1ms/step - loss: 1.4195 - accuracy: 0.5545
Epoch 3/1000
4/4 [==============================] - 0s 997us/step - loss: 1.2615 - accuracy: 0.6832
Epoch 4/1000
4/4 [==============================] - 0s 746us/step - loss: 1.1189 - accuracy: 0.7426
Epoch 5/1000
4/4 [==============================] - 0s 997us/step - loss: 1.0139 - accuracy: 0.7624
Epoch 6/1000
4/4 [==============================] - 0s 748us/step - loss: 0.9409 - accuracy: 0.8416
Epoch 7/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.8712 - accuracy: 0.8119
Epoch 8/1000
4/4 [==============================] - 0s 748us/step - loss: 0.8259 - accuracy: 0.8020
Epoch 9/1000
4/4 [==============================] - 0s 748us/step - loss: 0.7862 - accuracy: 0.8515
Epoch 10/1000
4/4 [==============================] - 0s 997us/step - loss: 0.7444 - accuracy: 0.8218
Epoch

4/4 [==============================] - 0s 803us/step - loss: 0.2382 - accuracy: 0.9505
Epoch 83/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.2390 - accuracy: 0.9505
Epoch 84/1000
4/4 [==============================] - 0s 748us/step - loss: 0.2388 - accuracy: 0.9406
Epoch 85/1000
4/4 [==============================] - 0s 998us/step - loss: 0.2403 - accuracy: 0.9505
Epoch 86/1000
4/4 [==============================] - 0s 995us/step - loss: 0.2343 - accuracy: 0.9505
Epoch 87/1000
4/4 [==============================] - 0s 997us/step - loss: 0.2316 - accuracy: 0.9406
Epoch 88/1000
4/4 [==============================] - 0s 812us/step - loss: 0.2284 - accuracy: 0.9406
Epoch 89/1000
4/4 [==============================] - 0s 748us/step - loss: 0.2282 - accuracy: 0.9505
Epoch 90/1000
4/4 [==============================] - 0s 748us/step - loss: 0.2248 - accuracy: 0.9505
Epoch 91/1000
4/4 [==============================] - 0s 997us/step - loss: 0.2241 - accuracy: 0.9505
Epoch 

4/4 [==============================] - 0s 1ms/step - loss: 0.1477 - accuracy: 0.9802
Epoch 163/1000
4/4 [==============================] - 0s 748us/step - loss: 0.1471 - accuracy: 0.9802
Epoch 164/1000
4/4 [==============================] - 0s 747us/step - loss: 0.1458 - accuracy: 0.9802
Epoch 165/1000
4/4 [==============================] - 0s 997us/step - loss: 0.1447 - accuracy: 0.9802
Epoch 166/1000
4/4 [==============================] - 0s 997us/step - loss: 0.1445 - accuracy: 0.9901
Epoch 167/1000
4/4 [==============================] - 0s 998us/step - loss: 0.1438 - accuracy: 0.9802
Epoch 168/1000
4/4 [==============================] - 0s 997us/step - loss: 0.1429 - accuracy: 0.9802
Epoch 169/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.1425 - accuracy: 0.9802
Epoch 170/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.1432 - accuracy: 0.9802
Epoch 171/1000
4/4 [==============================] - 0s 997us/step - loss: 0.1409 - accuracy: 0.9802
E

4/4 [==============================] - 0s 997us/step - loss: 0.1060 - accuracy: 1.0000
Epoch 243/1000
4/4 [==============================] - 0s 998us/step - loss: 0.1058 - accuracy: 1.0000
Epoch 244/1000
4/4 [==============================] - 0s 748us/step - loss: 0.1056 - accuracy: 1.0000
Epoch 245/1000
4/4 [==============================] - 0s 997us/step - loss: 0.1057 - accuracy: 1.0000
Epoch 246/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.1077 - accuracy: 0.9901
Epoch 247/1000
4/4 [==============================] - 0s 997us/step - loss: 0.1062 - accuracy: 1.0000
Epoch 248/1000
4/4 [==============================] - 0s 997us/step - loss: 0.1044 - accuracy: 1.0000
Epoch 249/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.1039 - accuracy: 1.0000
Epoch 250/1000
4/4 [==============================] - 0s 998us/step - loss: 0.1030 - accuracy: 1.0000
Epoch 251/1000
4/4 [==============================] - 0s 997us/step - loss: 0.1036 - accuracy: 1.0000

4/4 [==============================] - 0s 997us/step - loss: 0.0834 - accuracy: 1.0000
Epoch 323/1000
4/4 [==============================] - 0s 748us/step - loss: 0.0831 - accuracy: 1.0000
Epoch 324/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0833 - accuracy: 1.0000
Epoch 325/1000
4/4 [==============================] - 0s 748us/step - loss: 0.0837 - accuracy: 1.0000
Epoch 326/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0828 - accuracy: 1.0000
Epoch 327/1000
4/4 [==============================] - 0s 750us/step - loss: 0.0826 - accuracy: 1.0000
Epoch 328/1000
4/4 [==============================] - 0s 748us/step - loss: 0.0824 - accuracy: 1.0000
Epoch 329/1000
4/4 [==============================] - 0s 997us/step - loss: 0.0819 - accuracy: 1.0000
Epoch 330/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0816 - accuracy: 1.0000
Epoch 331/1000
4/4 [==============================] - 0s 748us/step - loss: 0.0823 - accuracy: 1.0000
E

4/4 [==============================] - 0s 750us/step - loss: 0.0687 - accuracy: 1.0000
Epoch 403/1000
4/4 [==============================] - 0s 998us/step - loss: 0.0702 - accuracy: 1.0000
Epoch 404/1000
4/4 [==============================] - 0s 998us/step - loss: 0.0681 - accuracy: 1.0000
Epoch 405/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0679 - accuracy: 1.0000
Epoch 406/1000
4/4 [==============================] - 0s 748us/step - loss: 0.0678 - accuracy: 1.0000
Epoch 407/1000
4/4 [==============================] - 0s 997us/step - loss: 0.0695 - accuracy: 1.0000
Epoch 408/1000
4/4 [==============================] - 0s 997us/step - loss: 0.0682 - accuracy: 1.0000
Epoch 409/1000
4/4 [==============================] - 0s 997us/step - loss: 0.0698 - accuracy: 1.0000
Epoch 410/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0685 - accuracy: 1.0000
Epoch 411/1000
4/4 [==============================] - 0s 748us/step - loss: 0.0678 - accuracy: 1.0000

Epoch 483/1000
4/4 [==============================] - 0s 2ms/step - loss: 0.0580 - accuracy: 1.0000
Epoch 484/1000
4/4 [==============================] - 0s 748us/step - loss: 0.0578 - accuracy: 1.0000
Epoch 485/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0580 - accuracy: 1.0000
Epoch 486/1000
4/4 [==============================] - 0s 748us/step - loss: 0.0582 - accuracy: 1.0000
Epoch 487/1000
4/4 [==============================] - 0s 997us/step - loss: 0.0582 - accuracy: 1.0000
Epoch 488/1000
4/4 [==============================] - 0s 748us/step - loss: 0.0576 - accuracy: 1.0000
Epoch 489/1000
4/4 [==============================] - 0s 748us/step - loss: 0.0576 - accuracy: 1.0000
Epoch 490/1000
4/4 [==============================] - 0s 997us/step - loss: 0.0575 - accuracy: 1.0000
Epoch 491/1000
4/4 [==============================] - 0s 748us/step - loss: 0.0574 - accuracy: 1.0000
Epoch 492/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0574 - acc

4/4 [==============================] - 0s 997us/step - loss: 0.0506 - accuracy: 1.0000
Epoch 564/1000
4/4 [==============================] - 0s 997us/step - loss: 0.0504 - accuracy: 1.0000
Epoch 565/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0503 - accuracy: 1.0000
Epoch 566/1000
4/4 [==============================] - 0s 998us/step - loss: 0.0500 - accuracy: 1.0000
Epoch 567/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0499 - accuracy: 1.0000
Epoch 568/1000
4/4 [==============================] - 0s 748us/step - loss: 0.0502 - accuracy: 1.0000
Epoch 569/1000
4/4 [==============================] - 0s 748us/step - loss: 0.0501 - accuracy: 1.0000
Epoch 570/1000
4/4 [==============================] - 0s 997us/step - loss: 0.0501 - accuracy: 1.0000
Epoch 571/1000
4/4 [==============================] - 0s 744us/step - loss: 0.0498 - accuracy: 1.0000
Epoch 572/1000
4/4 [==============================] - 0s 748us/step - loss: 0.0497 - accuracy: 1.0000

4/4 [==============================] - 0s 748us/step - loss: 0.0453 - accuracy: 1.0000
Epoch 644/1000
4/4 [==============================] - 0s 997us/step - loss: 0.0448 - accuracy: 1.0000
Epoch 645/1000
4/4 [==============================] - 0s 998us/step - loss: 0.0449 - accuracy: 1.0000
Epoch 646/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0446 - accuracy: 1.0000
Epoch 647/1000
4/4 [==============================] - 0s 748us/step - loss: 0.0444 - accuracy: 1.0000
Epoch 648/1000
4/4 [==============================] - 0s 998us/step - loss: 0.0443 - accuracy: 1.0000
Epoch 649/1000
4/4 [==============================] - 0s 748us/step - loss: 0.0442 - accuracy: 1.0000
Epoch 650/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0440 - accuracy: 1.0000
Epoch 651/1000
4/4 [==============================] - 0s 997us/step - loss: 0.0438 - accuracy: 1.0000
Epoch 652/1000
4/4 [==============================] - 0s 998us/step - loss: 0.0436 - accuracy: 1.0000

4/4 [==============================] - 0s 998us/step - loss: 0.0395 - accuracy: 1.0000
Epoch 724/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0397 - accuracy: 1.0000
Epoch 725/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0396 - accuracy: 1.0000
Epoch 726/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0397 - accuracy: 1.0000
Epoch 727/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0395 - accuracy: 1.0000
Epoch 728/1000
4/4 [==============================] - 0s 995us/step - loss: 0.0393 - accuracy: 1.0000
Epoch 729/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0393 - accuracy: 1.0000
Epoch 730/1000
4/4 [==============================] - 0s 998us/step - loss: 0.0393 - accuracy: 1.0000
Epoch 731/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0393 - accuracy: 1.0000
Epoch 732/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0392 - accuracy: 1.0000
Epoch 733

4/4 [==============================] - 0s 3ms/step - loss: 0.0361 - accuracy: 1.0000
Epoch 805/1000
4/4 [==============================] - 0s 2ms/step - loss: 0.0359 - accuracy: 1.0000
Epoch 806/1000
4/4 [==============================] - 0s 998us/step - loss: 0.0358 - accuracy: 1.0000
Epoch 807/1000
4/4 [==============================] - 0s 2ms/step - loss: 0.0356 - accuracy: 1.0000
Epoch 808/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0356 - accuracy: 1.0000
Epoch 809/1000
4/4 [==============================] - 0s 997us/step - loss: 0.0354 - accuracy: 1.0000
Epoch 810/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0357 - accuracy: 1.0000
Epoch 811/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0354 - accuracy: 1.0000
Epoch 812/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0354 - accuracy: 1.0000
Epoch 813/1000
4/4 [==============================] - 0s 748us/step - loss: 0.0354 - accuracy: 1.0000
Epoch 814

4/4 [==============================] - 0s 998us/step - loss: 0.0328 - accuracy: 1.0000
Epoch 886/1000
4/4 [==============================] - 0s 748us/step - loss: 0.0328 - accuracy: 1.0000
Epoch 887/1000
4/4 [==============================] - 0s 747us/step - loss: 0.0330 - accuracy: 1.0000
Epoch 888/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0328 - accuracy: 1.0000
Epoch 889/1000
4/4 [==============================] - 0s 997us/step - loss: 0.0329 - accuracy: 1.0000
Epoch 890/1000
4/4 [==============================] - 0s 997us/step - loss: 0.0328 - accuracy: 1.0000
Epoch 891/1000
4/4 [==============================] - 0s 997us/step - loss: 0.0325 - accuracy: 1.0000
Epoch 892/1000
4/4 [==============================] - 0s 998us/step - loss: 0.0326 - accuracy: 1.0000
Epoch 893/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0326 - accuracy: 1.0000
Epoch 894/1000
4/4 [==============================] - 0s 997us/step - loss: 0.0324 - accuracy: 1.0000

4/4 [==============================] - 0s 748us/step - loss: 0.0304 - accuracy: 1.0000
Epoch 966/1000
4/4 [==============================] - 0s 993us/step - loss: 0.0304 - accuracy: 1.0000
Epoch 967/1000
4/4 [==============================] - 0s 748us/step - loss: 0.0304 - accuracy: 1.0000
Epoch 968/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0304 - accuracy: 1.0000
Epoch 969/1000
4/4 [==============================] - 0s 2ms/step - loss: 0.0303 - accuracy: 1.0000
Epoch 970/1000
4/4 [==============================] - 0s 997us/step - loss: 0.0303 - accuracy: 1.0000
Epoch 971/1000
4/4 [==============================] - 0s 997us/step - loss: 0.0301 - accuracy: 1.0000
Epoch 972/1000
4/4 [==============================] - 0s 998us/step - loss: 0.0300 - accuracy: 1.0000
Epoch 973/1000
4/4 [==============================] - 0s 748us/step - loss: 0.0299 - accuracy: 1.0000
Epoch 974/1000
4/4 [==============================] - 0s 997us/step - loss: 0.0300 - accuracy: 1.0000

In [39]:
# 자료 하나 예측
test_data = np.array([[0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0]])
print(tf.model.predict(test_data), tf.model.predict_classes(test_data))

[[9.1043493e-04 1.2720930e-03 7.6806745e-03 9.8383498e-01 4.8145042e-03
  6.0410616e-07 1.4867248e-03]] [3]


In [40]:
pred = tf.model.predict_classes(x_data)
for p, y in zip(pred, y_data.flatten()):
    print("[{}] Prediction: {} True Y: {}".format(p==int(y), p, int(y)))

[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 3 True Y: 3
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 3 True Y: 3
[True] Prediction: 3 True Y: 3
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 1 True Y: 1
[True] Prediction: 3 True Y: 3
[True] Prediction: 6 True Y: 6
[True] Prediction: 6 True Y: 6
[True] Prediction: 6 True Y: 6
[True] Prediction: 1 True Y: 1
[True] Prediction: 0 True Y: 0
[True] Prediction: 3 True Y: 3
[True] Prediction: 0 True Y: 0
[True] Prediction: 1 True Y: 1
[True] Prediction: 1 True Y: 1
[True] Prediction: 0 True Y: 0
[True] Prediction: 1 True Y: 1
[True] Prediction: 5 True Y: 5
[True] Prediction: 4 True Y: 4
[True] Prediction: 4 True Y: 4
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 5 True Y: 5
[True] Prediction: 0 True Y: 0
[True] P