In [1]:
import tensorflow.compat.v1 as tf 
tf.disable_v2_behavior()

Instructions for updating:
non-resource variables are not supported in the long term


In [5]:
tf.set_random_seed(777) # 실습을 위해 임의값 설정, 

# 샘플 데이터 셋 설정
x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]

y_data =[152., 185, 180., 196., 142.,] 

# placeholder : 선언과 동시에 초기화 되는 것이 아닌 선언 후 그 다음 값을 전달
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)

Y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1]), name = 'weight1') # 하나의 값으로 준다.
w2 = tf.Variable(tf.random_normal([1]), name = 'weight2')
w3 = tf.Variable(tf.random_normal([1]), name = 'weight3')
b = tf.Variable(tf.random_normal([1]), name = 'bias')

hypothesis = x1*w1 + x2*w2 + x3*w3 + b

# cost/loss 함수
cost = tf.reduce_mean(tf.square(hypothesis -Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5) # 0.001로 쓰는 것을 1e-5로 표현 
# 가장 작은 learning late를 찾는다.
train = optimizer.minimize(cost)



sess=tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                  feed_dict={x1:x1_data, x2:x2_data, x3:x3_data, Y:y_data})
    if step % 10 == 0:
        print(step , "Cost: ", cost_val, "\nPrediction:\n", hy_val)
    

- 2000번을 시도 했을 때, cost 비용이 줄어 든다. 
- 예측값은  [154.52213 182.23383 181.2558  199.76697 135.95403] 로 실제 값 [152., 185, 180., 196., 142.,] 비슷하다. 
- 하지만 이 방식은 나중에 x가 수백개씩,,.많아 지면 비효율적이기 때문에 주로 metrix를 사용한다.

방법2 : matrix 사용

In [5]:
tf.set_random_seed(777)

# 데이터 셋팅
x_data = [
    [73., 80., 75.],
    [93., 88., 93.],
    [89., 91., 90.],
    [96., 98., 100.],
    [73., 66., 70.]]

y_data = [
    [152.],
    [185.],
    [180.],
    [196.],
    [142.]]

X = tf.placeholder(tf.float32, shape=[None, 3]) # None = N개의 값을 가질 것이다. 값의 갯수를 정해주지 않을때 사용 
Y = tf.placeholder(tf.float32, shape=[None, 1])

# Weight, bias 변수 지정
W = tf.Variable(tf.random_normal([3,1]), name = 'weight')
b = tf.Variable(tf.random_normal([1]), name= 'bias')

# 회귀식 
hypothesis = tf.matmul(X,W) + b

# cost/loss 항수 설정
cost = tf.reduce_mean(tf.square(hypothesis-Y))

# 최소화 
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# session 연결 
sess = tf.Session()
sess.run(tf.global_variables_initializer())

# 실행 
for step in range(2001):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X:x_data, Y:y_data})
    if step %10 == 0 :
        print(step, " Cost: ", cost_val, "\nPrediction\n", hy_val)

0  Cost:  76825.016 
Prediction
 [[ -96.46343 ]
 [-109.81928 ]
 [-111.79769 ]
 [-119.038536]
 [ -84.00308 ]]
10  Cost:  3.124318 
Prediction
 [[148.72755]
 [184.87671]
 [178.57411]
 [197.16806]
 [140.77527]]
20  Cost:  2.4178557 
Prediction
 [[149.47223]
 [185.7665 ]
 [179.45363]
 [198.12483]
 [141.45346]]
30  Cost:  2.4146655 
Prediction
 [[149.4773 ]
 [185.76732]
 [179.45723]
 [198.12776]
 [141.45361]]
40  Cost:  2.4114656 
Prediction
 [[149.48013]
 [185.76547]
 [179.45819]
 [198.12779]
 [141.45174]]
50  Cost:  2.4083047 
Prediction
 [[149.48294]
 [185.76361]
 [179.45914]
 [198.12782]
 [141.44984]]
60  Cost:  2.4051797 
Prediction
 [[149.48573]
 [185.76176]
 [179.46008]
 [198.12787]
 [141.44797]]
70  Cost:  2.4020271 
Prediction
 [[149.48856]
 [185.75992]
 [179.46103]
 [198.12791]
 [141.4461 ]]
80  Cost:  2.398912 
Prediction
 [[149.49133]
 [185.75809]
 [179.46196]
 [198.12793]
 [141.44423]]
90  Cost:  2.395785 
Prediction
 [[149.4941 ]
 [185.75621]
 [179.46288]
 [198.12791]
 [141.44

1000  Cost:  2.1572313 
Prediction
 [[149.72081]
 [185.60675]
 [179.53993]
 [198.125  ]
 [141.29572]]
1010  Cost:  2.1550097 
Prediction
 [[149.72304]
 [185.60529]
 [179.54068]
 [198.1249 ]
 [141.29433]]
1020  Cost:  2.1528246 
Prediction
 [[149.72525]
 [185.60382]
 [179.54144]
 [198.12482]
 [141.29295]]
1030  Cost:  2.15063 
Prediction
 [[149.72748]
 [185.60237]
 [179.54222]
 [198.12474]
 [141.29158]]
1040  Cost:  2.1484413 
Prediction
 [[149.72969]
 [185.60092]
 [179.54297]
 [198.12465]
 [141.29022]]
1050  Cost:  2.1462722 
Prediction
 [[149.73189]
 [185.59947]
 [179.54373]
 [198.12456]
 [141.28885]]
1060  Cost:  2.144095 
Prediction
 [[149.73409]
 [185.59802]
 [179.54446]
 [198.12445]
 [141.28749]]
1070  Cost:  2.1419282 
Prediction
 [[149.73628]
 [185.59659]
 [179.54523]
 [198.12436]
 [141.28615]]
1080  Cost:  2.139769 
Prediction
 [[149.73846]
 [185.59514]
 [179.54597]
 [198.12425]
 [141.28479]]
1090  Cost:  2.137639 
Prediction
 [[149.74065]
 [185.5937 ]
 [179.54672]
 [198.12418]

matrix를 사용할때도 앞의 경우와 마찬가지로 cost가 점점 줄어들고, 예측값은 실제 y 값과 가까워지는 것을 확인할 수 있다.

외부 파일 데이터 사용하기

방법 1. numpy 사용 

In [15]:
import numpy as np

tf.set_random_seed(777)

# numpy 의 단점은 모든 데이터가 같은 타입이어야 함. 
xy = np.loadtxt('../../../DeepLearningZeroToAll/DeepLearningZeroToAll-master/data-01-test-score.csv', delimiter=',', dtype=np.float32)

x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

print("x_data shape", x_data.shape,"\n",x_data)1
print("y_data shape", y_data.shape,"\n",y_data)

x_data shape (25, 3) 
 [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]
 [ 69.  70.  73.]
 [ 70.  65.  74.]
 [ 93.  95.  91.]
 [ 79.  80.  73.]
 [ 70.  73.  78.]
 [ 93.  89.  96.]
 [ 78.  75.  68.]
 [ 81.  90.  93.]
 [ 88.  92.  86.]
 [ 78.  83.  77.]
 [ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]]
y_data shape (25, 1) 
 [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]]


In [19]:
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3,1]), name = 'weight')
b = tf.Variable(tf.random_normal([1]), name = 'bias')

hypothesis = tf.matmul(X, W) + b

cost = tf.reduce_mean(tf.square(hypothesis-Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)
sess = tf.Session()

sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                  feed_dict={X:x_data, Y:y_data})
    
    if step % 100 == 0:
        print(step, "Cost :", cost_val, "\nPrediction\n", hy_val)


0 Cost : 207488.16 
Prediction
 [[-270.7529 ]
 [-330.78342]
 [-323.07275]
 [-354.08548]
 [-251.55775]
 [-189.12744]
 [-266.54678]
 [-199.6378 ]
 [-312.901  ]
 [-294.96216]
 [-256.1025 ]
 [-255.61302]
 [-331.70108]
 [-272.85117]
 [-268.78613]
 [-337.25223]
 [-258.80313]
 [-320.23584]
 [-315.0468 ]
 [-281.62057]
 [-312.7131 ]
 [-312.0261 ]
 [-297.05148]
 [-268.06204]
 [-341.03015]]
100 Cost : 43.978497 
Prediction
 [[157.26445]
 [183.9834 ]
 [183.9542 ]
 [198.24434]
 [141.00296]
 [100.54456]
 [147.00575]
 [107.09497]
 [168.4315 ]
 [151.2056 ]
 [142.2894 ]
 [137.40845]
 [191.99126]
 [162.31378]
 [146.73193]
 [185.2171 ]
 [155.56767]
 [176.07907]
 [184.14607]
 [165.0277 ]
 [172.24068]
 [171.00888]
 [165.24615]
 [163.16252]
 [192.3489 ]]
200 Cost : 40.903633 
Prediction
 [[157.05122]
 [184.0398 ]
 [183.83766]
 [198.25111]
 [141.01338]
 [100.79505]
 [147.12192]
 [107.32715]
 [168.72008]
 [151.79636]
 [142.35721]
 [137.66455]
 [191.73943]
 [161.93417]
 [146.91013]
 [185.3729 ]
 [155.14082]
 [

2000번을 시도했을때 cost는 점점 낮아지고, y 예측값은 실제 y값과 비슷함을 알 수 있다.

구축해놓은 모델로 임의의 값을 X 값을 넣었을때, y 값을 예측해보자.

In [20]:
# case 1 
print("Your score will be ", sess.run(hypothesis,
                                     feed_dict={X:[[100,70,101]]}))

Your score will be  [[180.57805]]


In [21]:
# case 2 : 여러개의 X값도 바로 예측 가능하다.  
print("Your score will be ", sess.run(hypothesis,
                                     feed_dict={X:[[60,70,110], [90,100,80]]}))

Your score will be  [[159.92867]
 [183.72685]]


방법 2. tensor의 queue runners 이용 

In [28]:
# 1. 파일을 불러옴 (파일 여러개의 리스트도 가능)
filename_queue = tf.train.string_input_producer(
        ['../../../DeepLearningZeroToAll/DeepLearningZeroToAll-master/data-01-test-score.csv'], shuffle=False, name='filename_queue')

# 2. File을 읽어올 Reader을 정의
reader= tf.TextLineReader()
key, value = reader.read(filename_queue)

# 3. value를 읽어와 어떻게 parsing할 것인지 정의
record_defaults = [[0.],[0.],[0.],[0.] ] ## 각각 필드마다 데이터 형식 정의 가능 # 여기선 float으로 정의
xy = tf.decode_csv(value, record_defaults=record_defaults)

# 4. tensorflow batch를 사용하여 데이터를 읽어옴
train_x_batch, train_y_batch = tf.train.batch([xy[0:-1], xy[-1:]], batch_size=10)

# 여기서부턴 동일
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.matmul(X, W) + b

cost = tf.reduce_mean(tf.square(hypothesis - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)

train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

# session에 연동. 
coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess=sess, coord=coord)

for step in range(2001):
    x_batch, y_batch = sess.run([train_x_batch, train_y_batch]) # 데이터를 펌프해서 가져온다.
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_batch, Y: y_batch})
    if step % 500 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

coord.request_stop()
coord.join(threads)

0 Cost:  82775.49 
Prediction:
 [[-119.873535]
 [-153.27794 ]
 [-146.17989 ]
 [-159.07573 ]
 [-119.54704 ]
 [ -89.52667 ]
 [-116.69645 ]
 [ -82.79748 ]
 [-145.495   ]
 [-135.65468 ]]
500 Cost:  21.438442 
Prediction:
 [[157.50952]
 [181.88358]
 [183.12039]
 [199.87836]
 [136.24377]
 [ 99.75966]
 [151.97293]
 [116.29696]
 [168.54059]
 [156.0866 ]]
1000 Cost:  15.745844 
Prediction:
 [[156.77135 ]
 [182.40254 ]
 [182.8874  ]
 [199.8655  ]
 [136.7902  ]
 [100.698135]
 [151.92659 ]
 [116.16973 ]
 [169.6459  ]
 [157.7683  ]]
1500 Cost:  11.999232 
Prediction:
 [[156.17043 ]
 [182.83324 ]
 [182.7024  ]
 [199.85052 ]
 [137.25117 ]
 [101.460144]
 [151.8689  ]
 [116.02796 ]
 [170.54353 ]
 [159.1148  ]]
2000 Cost:  9.522764 
Prediction:
 [[155.68033]
 [183.19159]
 [182.55554]
 [199.83447]
 [137.64108]
 [102.07995]
 [151.80464]
 [115.87938]
 [171.2738 ]
 [160.19366]]
