In [4]:
import tensorflow.compat.v1 as tf 
tf.disable_v2_behavior()

import numpy as np

In [5]:
tf.set_random_seed(777)

In [11]:
# training data set 
x_data = [[1, 2, 1],
          [1, 3, 2],
          [1, 3, 4],
          [1, 5, 5],
          [1, 7, 5],
          [1, 2, 5],
          [1, 6, 6],
          [1, 7, 7]]
y_data = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]

# 평가를 위해 아래 test dataset을 활용한다.
x_test = [[2, 1, 1],
          [3, 1, 2],
          [3, 3, 4]]
y_test = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1]]

In [13]:
X = tf.placeholder("float", [None, 3])
Y = tf.placeholder("float", [None, 3])

W = tf.Variable(tf.random_normal([3,3]))
b = tf.Variable(tf.random_normal([3]))

hypothesis = tf.nn.softmax(tf.matmul(X,W) + b)

cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)
# 정확도가 너무 크면(ex : 1.5) 무한대로 nan 값, 너무 작으면(ex : 1e-10) 제대로 min 값을 못찾고 작은 골짜기에서 멈춤. 
# optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

prediction = tf.argmax(hypothesis, 1)
is_correct = tf.equal(prediction, tf.argmax(Y, 1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    for step in range(201):
        # 예측 모형에 test dataset 적용
#         cost_val, W_val, = sess.run([cost, W, optimizer], feed_dict = {X:x_data, Y:y_data})
        cost_val, W_val, _ = sess.run([cost, W, optimizer], feed_dict={X: x_data, Y: y_data})
        print(step, cost_val, W_val)
        
    print("Prediction:", sess.run(prediction, feed_dict={X:x_test}))
    print("Accuracy:", sess.run(accuracy, feed_dict={X:x_test, Y:y_test}))        
                                  

0 10.527496 [[-0.83976614 -0.24057412 -0.7152096 ]
 [-0.2930086  -0.46021748  1.6287701 ]
 [ 0.66676027 -0.08336069  0.6954783 ]]
1 6.9123797 [[-0.8182902  -0.20402668 -0.77323306]
 [-0.13808629 -0.2871926   1.300823  ]
 [ 0.81879056  0.10293023  0.3571571 ]]
2 3.756608 [[-0.81655663 -0.17048472 -0.8085085 ]
 [-0.03407518 -0.12116213  1.0307814 ]
 [ 0.8945126   0.28337643  0.10098889]]
3 2.1274273 [[-0.851444   -0.14307798 -0.8010279 ]
 [-0.11427568  0.02649407  0.9633257 ]
 [ 0.78712744  0.44729877  0.04445171]]
4 1.5331161 [[-0.86510944 -0.13872838 -0.79171205]
 [-0.10627382  0.08023711  0.90158075]
 [ 0.774851    0.51268464 -0.00865773]]
5 1.4738891 [[-0.87417537 -0.15077367 -0.77060086]
 [-0.0840968   0.05006061  0.90958023]
 [ 0.78232753  0.49542317  0.00112723]]
6 1.457331 [[-0.88858396 -0.154741   -0.752225  ]
 [-0.0872226   0.06083121  0.9019354 ]
 [ 0.7631107   0.5184776  -0.00271043]]
7 1.4429501 [[-0.89812416 -0.16414455 -0.73328125]
 [-0.06772903  0.04526864  0.8980044 ]
 [

 [ 0.72895133  0.63167626 -0.08174967]]
149 0.696954 [[-1.9889795  -0.77048993  0.9639197 ]
 [ 0.37263918  0.17615005  0.32675496]
 [ 0.7300052   0.6315617  -0.08268894]]
150 0.6953325 [[-1.9941416  -0.77217746  0.9707694 ]
 [ 0.37362516  0.17714843  0.3247706 ]
 [ 0.73106545  0.6314504  -0.08363791]]
151 0.6937293 [[-1.9992845  -0.77384275  0.97757757]
 [ 0.37459794  0.178135    0.32281125]
 [ 0.7321319   0.6313425  -0.08459638]]
152 0.69214404 [[-2.0044084  -0.7754861   0.98434466]
 [ 0.37555778  0.17910981  0.32087657]
 [ 0.7332045   0.6312377  -0.08556418]]
153 0.69057643 [[-2.0095131  -0.7771077   0.99107116]
 [ 0.37650478  0.18007308  0.3189663 ]
 [ 0.734283    0.6311361  -0.08654112]]
154 0.6890259 [[-2.0145993  -0.7787079   0.9977575 ]
 [ 0.3774392   0.18102485  0.3170801 ]
 [ 0.7353675   0.63103753 -0.08752701]]
155 0.68749243 [[-2.019667   -0.7802869   1.0044042 ]
 [ 0.37836102  0.18196541  0.31521773]
 [ 0.73645765  0.63094205 -0.08852169]]
156 0.6859757 [[-2.0247164  -0.781

정규화

In [5]:
# 값의 범위가 너무 크거나 작을때는 정규화가 필요하다.
# 예를 들어, 아래처럼 값의 범위가 클때! 정규화를 적용한다.

tf.set_random_seed(777)

def min_max_scaler(data):
    numerator = data - np.min(data,0)
    denominator = np.max(data, 0) - np.min(data,0)
    return numerator / (denominator + 1e-7)

xy = np.array([[828.659973, 833.450012, 908100, 828.349976, 831.659973],
               [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
               [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
               [816, 820.958984, 1008100, 815.48999, 819.23999],
               [819.359985, 823, 1188100, 818.469971, 818.97998],
               [819, 823, 1198100, 816, 820.450012],
               [811.700012, 815.25, 1098100, 809.780029, 813.669983],
               [809.51001, 816.659973, 1398100, 804.539978, 809.559998]])
# 정규화 적용 
xy = min_max_scaler(xy)
print(xy)

[[0.99999999 0.99999999 0.         1.         1.        ]
 [0.70548491 0.70439552 1.         0.71881782 0.83755791]
 [0.54412549 0.50274824 0.57608696 0.606468   0.6606331 ]
 [0.33890353 0.31368023 0.10869565 0.45989134 0.43800918]
 [0.51436    0.42582389 0.30434783 0.58504805 0.42624401]
 [0.49556179 0.42582389 0.31521739 0.48131134 0.49276137]
 [0.11436064 0.         0.20652174 0.22007776 0.18597238]
 [0.         0.07747099 0.5326087  0.         0.        ]]


- 실제 사례 적용
- softmax 적용 (확률적으로 정답인 것에 1을 주는 것)
- epoch : 전체 데이터 셋을 한번 학습 시키는 것. 
- batch size : 메모리에 한번에 넣을 수 없기 때문에, 나눠서 모델 적용 

In [23]:
tf.set_random_seed(777)

# mnist data set 불러오기. 참고 https://www.tensorflow.org/datasets/overview
# 기존 불러오는 방식은 사라졌다!!! 불러와서 데이터 셋팅하는 예제는 #https://excelsior-cjh.tistory.com/149 를 참고 하였다.!
(train_x, train_y), (test_x, test_y) = tf.keras.datasets.mnist.load_data()


In [32]:
nb_classes = 10
## Train DataSet
# 변경 (60000 * 28 * 28) -> (60000 * 784)
train_x = train_x.reshape([train_x.shape[0], -1])
# 0~255로 표현되는 image 데이터이기 때문에 float32로 데이터 타입을 설정하고, 255로 나눠준다.
train_x = train_x.astype('float32')/255
# y 값을 one hot enconding 작업 10개의 클래스(숫자 0~9)로 나눈다.
train_y = tf.keras.utils.to_categorical(train_y, num_classes=nb_classes)

## Test DataSet
# 변경 (60000 * 28 * 28) -> (60000 * 784)
test_x = test_x.reshape([test_x.shape[0], -1])
# 0~255로 표현되는 image 데이터이기 때문에 float32로 데이터 타입을 설정하고, 255로 나눠준다.
test_x = test_x.astype('float32')/255
# y 값을 one hot enconding 작업 10개의 클래스(숫자 0~9)로 나눈다.
test_y = tf.keras.utils.to_categorical(test_y, num_classes=nb_classes)

In [33]:
MINIBATCH_SIZE = 100
# buffer_size 
buffter_size = train_x.shape[0] + test_x.shape[0]
# 데이터 자르기 
dataset = tf.data.Dataset.from_tensor_slices(({"image":train_x}, train_y))
# batchsize만큼 반복하여 buffer size만큼 data shuffer 
dataset = dataset.shuffle(buffter_size).repeat().batch(MINIBATCH_SIZE)
iterator = dataset.make_one_shot_iterator()
next_batch = iterator.get_next()

In [34]:
## 모델 설정
x = tf.placeholder(tf.float32, [None, 784])
y_true = tf.placeholder(tf.float32, [None, nb_classes])

W = tf.Variable(tf.random_normal([784, nb_classes]))
# b = tf.Variable(tf.random_normal([nb_classes]))

# y 예측값
# hypothesis = tf.nn.softmax(tf.matmul(X,W) + b)
y_pred  = tf.matmul(x,W)

# Cost(Loss) Function
# cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1)) # cross entropy
cross_entropy = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits_v2(logits=y_pred, labels = y_true))

# Gradient Step(Optimze)
# train = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)
gd_step = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

# is_correct = tf.equal(tf.argmax(hypothesis, 1), tf.argmax(Y, 1))
is_correct = tf.equal(tf.argmax(y_pred, 1), tf.argmax(y_true, 1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

# 앞에서 설정.
# num_epochs = 15
# batch_size = 100
# num_iterations = int(train_x.shape[0] / batch_size)

In [42]:
num_step = 100
# %%time
# 학습
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    for step in range(num_step):
        batch_xs, batch_ys = sess.run(next_batch)
        sess.run(gd_step, feed_dict={x:batch_xs['image'], y_true: batch_ys})
        
        if(step +1) % 100 ==0:
            print(step+1, '|', sess.run(cross_entropy, feed_dict={x:batch_xs['image'], y_true: batch_size}))
    # 테스트
    ans = sess.run(accuracy, feed_dict={x:test_x, y_true:test_y})
    
print('---------------------')
print("Accuracy : {.2f}%".format(ans*100))

NameError: name 'gd_step' is not defined