In [1]:
import tensorflow as tf

In [4]:
# 텐서플로우 버전 확인
tf.__version__

'2.3.0'

In [7]:
# tf.Session()은 1.0.0 version에서 사용하던 것. 2.0 version 이후엔 그냥 실행하면된다.
# sess = tf.Session() 
hello= "Hello, Tensor"
tf.print(hello)

Hello, Tensor


In [8]:
node1 = tf.constant(3.0, tf.float32)
node2 = tf.constant(4.0)
node3 = tf.add(node1, node2)

In [9]:
print("node1:", node1,"node2:", node2  )
print("node3:", node3 )

node1: tf.Tensor(3.0, shape=(), dtype=float32) node2: tf.Tensor(4.0, shape=(), dtype=float32)
node3: tf.Tensor(7.0, shape=(), dtype=float32)


In [22]:
import numpy as np

# a = tf.placeholder(tf.float32)
# b = tf.placeholder(tf.float32)

@tf.function
def addfunc(a,b):
    return a + b

a = tf.constant(1)
b = tf.constant(2)
print(addfunc(a,b))

c = tf.constant([1,2])
d = tf.constant([3,4])
print(addfunc(c,d))

e = tf.constant([[1,2,3], [4,5,6]])
f = tf.constant([[4,5,6], [7,8,9]])
print(addfunc(e,f))


tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([4 6], shape=(2,), dtype=int32)
tf.Tensor(
[[ 5  7  9]
 [11 13 15]], shape=(2, 3), dtype=int32)


In [24]:
print(addfunc(3,7)*3)

tf.Tensor(30, shape=(), dtype=int32)
