In [2]:
import tensorflow.compat.v1 as tf 
tf.disable_v2_behavior()

import numpy as np
import pprint

Instructions for updating:
non-resource variables are not supported in the long term


In [3]:
tf.set_random_seed(777)
pp = pprint.PrettyPrinter(indent=4)
sess = tf.InteractiveSession()

In [4]:
## Simple Array
# 1차원일 경우
t = np.array([0., 1., 2., 3., 4., 5., 6.])
pp.pprint(t)
print(t.ndim) # rank, 차원, 1차원
print(t.shape) # shape, 데이터 갯수
print(t[0], t[1], t[-1]) # index -1 은 제일 마지막 것을 의미 
print(t[2:5], t[4:-1]) 
print(t[:2], t[3:])

array([0., 1., 2., 3., 4., 5., 6.])
1
(7,)
0.0 1.0 6.0
[2. 3. 4.] [4. 5.]
[0. 1.] [3. 4. 5. 6.]


In [5]:
# 2차원일 경우

t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
pp.pprint(t)
print(t.ndim) # rank, 차원, 2차원
print(t.shape) # shape, 데이터 갯수

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])
2
(4, 3)


In [6]:
t = tf.constant([1,2,3,4])
tf.shape(t).eval() # element 개수가 4개인 1차원 배열 

array([4])

In [8]:
t = tf.constant([[1,2],[3,4]])
tf.shape(t).eval() # element 개수가 4개인 1차원 배열 

array([2, 2])

In [9]:
t = tf.constant([[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],[[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]])
tf.shape(t).eval() # rank 4, x, y, z  # axis 축 가장안쪽에 값을 불러오는 것이 제일 큰값, (제일 안쪽 값은-1)

array([1, 2, 3, 4])

matmul vs multipy
matmul : matrix의 곱 / multipy : 원소들의 곱 두가지 결과가 다르다.

In [20]:
matrix1 = tf.constant([[1., 2.],[3., 4.]])
matrix2 = tf.constant([[1.], [2.]])
print('matrix1 ',matrix1.shape )
print('matrix2 ',matrix2.shape )
print('---- matmul vs multipy ---- ')
print('matmul \n', tf.matmul(matrix1, matrix2).eval())
print('multipy \n ', (matrix1* matrix2).eval())

matrix1  (2, 2)
matrix2  (2, 1)
---- matmul vs multipy ---- 
matmul 
 [[ 5.]
 [11.]]
multipy 
  [[1. 2.]
 [6. 8.]]


- broad casting: shape이 다르더라도 연산을 할 수 있게 해주는 것. 
- `주의` 잘 사용하면 유용하지만, 잘못 사용하면 굉장히 위험한 기능!!

In [23]:
# 더할 수 있는 경우 이 같은 경우엔 
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2., 2.]])
(matrix1 +  matrix2).eval()

array([[5., 5.]], dtype=float32)

In [24]:
# 차원이 달라서 덧셈이 불가능할 것 같지만, broadcasting을 활용하여 계산이 가능하다. 
matrix1 = tf.constant([[1., 2.]])
matrix2 = tf.constant([[3.]])
(matrix1 +  matrix2).eval()

array([[4., 5.]], dtype=float32)

In [25]:
matrix1 = tf.constant([[1., 2.]])
matrix2 = tf.constant([[3.],[4.]])
(matrix1 +  matrix2).eval()

array([[4., 5.],
       [5., 6.]], dtype=float32)

- reduce_mean 기능
- reduce_mean : 평균을 구하는데 줄여서 구해준다.
- reduce_mean : 합계을 구하는데 줄여서 구해준다.

In [26]:
# 변수가 int형이기 때문에, 평균값 결과도 1로 계산
tf.reduce_mean([1,2], axis=0).eval()

1

In [27]:
# 보통 평균을 구하면 소수점이 나올수 있기때문에 변수는 float형으로!
x = [ [1., 2.], [3., 4.]]
tf.reduce_mean(x).eval()

2.5

In [28]:
# aixs 활용하여 평균 값 도출
# axis 0 은 컬럼 데이터, aixs 1 은 행 데이터 
# reduce_mean 은 축에 따라 계산 가능함.
# reduce_sum 도 동일
tf.reduce_mean(x, axis=0).eval() # 1,3 / 2,4

array([2., 3.], dtype=float32)

In [29]:
tf.reduce_mean(x, axis=1).eval() # 1,2 / 3,4 # 여기선 axis=1 이 제일 안쪽 값이므로, axis=-1과 동일

array([1.5, 3.5], dtype=float32)

argmax : 최댓값의 위치(index)를 구해준다.

In [33]:
x = [ [0, 1 ,2],
     [2, 1, 0]]
tf.argmax(x, axis=0).eval()

array([1, 0, 0], dtype=int64)

In [35]:
tf.argmax(x, axis=1).eval() # axis = -1 값과 동일 

array([2, 0], dtype=int64)

reshape : 가장 많이 사용하는 기능****

In [37]:
t = np.array([[[0, 1, 2], 
               [3, 4, 5]],
              
              [[6, 7, 8], 
               [9, 10, 11]]])
t.shape

(2, 2, 3)

행열을 다시 만들고 싶으면 shape의 모양을 재설정 한다.

In [38]:
tf.reshape(t, shape=[-1, 3]).eval() # -1 : 맘대로, 3 : 보통 제일 안쪽에 있는 값은 그냥 둔다. 그래서 섞이거나 하진 않음.

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [39]:
tf.reshape(t, shape=[-1,1, 3]).eval() # -1 : 맘대로

array([[[ 0,  1,  2]],

       [[ 3,  4,  5]],

       [[ 6,  7,  8]],

       [[ 9, 10, 11]]])

In [41]:
# squeeze 하고 싶을때, 하나로 나타내고 싶을때
tf.squeeze([[0], [1], [3]]).eval()

array([0, 1, 3])

In [42]:
# demension 을 추가하고 싶을때 
tf.expand_dims([0,1,2], 1).eval() # 1차원 늘린다.

array([[0],
       [1],
       [2]])

one-hot encoding 기능
- categorial 변수를 0과 1로 표현

In [43]:
tf.one_hot([[0], [1], [2], [0]], depth=3 ).eval()

array([[[1., 0., 0.]],

       [[0., 1., 0.]],

       [[0., 0., 1.]],

       [[1., 0., 0.]]], dtype=float32)

In [45]:
# onehot을 적용하면 rank가 자동을 1차원이 늘어나는데 싫으면 reshape 하면됨.
t = tf.one_hot([[0], [1], [2], [0]], depth=3 )
tf.reshape(t, shape=[-1,3]).eval()

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]], dtype=float32)

casting : 데이터형을 casting
- 문자를 숫자로 바꿔주기도함.
- T/F 값을 숫자로 바꿔 카운트 할때 사용

In [46]:
tf.cast([1.8, 2.2, 3.3, 4.9], tf.int32).eval()

array([1, 2, 3, 4])

In [47]:
tf.cast([True, False, 1==1, 0==1], tf.int32).eval()

array([1, 0, 1, 0])

stack : 데이터를 쌓아줌.

In [48]:
x = [1, 4]
y = [2, 5]
z = [3, 6]

tf.stack([x, y, z]).eval()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [50]:
#축설정을 통해 가로, 세로를 바꿔줄수도 있음
tf.stack([x,y,z], axis=1).eval()

array([[1, 2, 3],
       [4, 5, 6]])

Ones and Zeros like : 어떤 shape을 그대로 가져와, 0또는 1의 값으로 채운다.

In [51]:
x = [[0, 1, 2],
     [2, 1, 0]]

tf.ones_like(x).eval()

array([[1, 1, 1],
       [1, 1, 1]])

In [52]:
tf.zeros_like(x).eval()

array([[0, 0, 0],
       [0, 0, 0]])

zip : 배열의 원소를 하나씩 꺼내줌.

In [54]:
for x,y in zip([1,2,3], [4,5,6]):
    print(x,y)

1 4
2 5
3 6


In [55]:
for x,y,z in zip([1,2,3], [4,5,6], [7,8,9]):
    print(x, y, z)

1 4 7
2 5 8
3 6 9
