## Neural Network 실습

In [1]:
import tensorflow.compat.v1 as tf 
tf.disable_v2_behavior()
import numpy as np

Instructions for updating:
non-resource variables are not supported in the long term


In [2]:
tf.set_random_seed(777)

x_data=np.array([[0,0],[0,1],[1,0],[1,1]], dtype=np.float32)
y_data=np.array([[0],[1],[1],[0]], dtype=np.float32)

In [3]:
# 변수 선언
X = tf.placeholder(tf.float32, [None,2]) # x1, x2 
Y = tf.placeholder(tf.float32, [None,1]) # y
W = tf.Variable(tf.random_normal([2,1]), name ="weight") # x변수 2개, y변수 1개
b = tf.Variable(tf.random_normal([1]), name = "bias")

In [4]:
# logistic regression
hypothesis = tf.sigmoid(tf.matmul(X,W) + b)

# cost/loss function
cost = -tf.reduce_mean( Y * tf.log(hypothesis) + (1-Y)*tf.log(1-hypothesis))
train = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

# Accuracy computation 
# 만약 hypotesis 결과가 0.5 이상이면 False
predicted = tf.cast(hypothesis > 0.5, dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))

In [5]:
# 그래프 실행
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    for step in range(10001):
        _, cost_val, w_val = sess.run(
            [train, cost, W] , feed_dict={X:x_data, Y:y_data}
        )
        if step % 100 == 0:
            print(step, cost_val, w_val)
            
    h, c, a = sess.run(
        [hypothesis, predicted, accuracy], feed_dict={X:x_data, Y: y_data}
    )
    
    print("\nHypotesis: ", h, "\nCorrect: ", c, "\nAccuracy: ", a )

0 0.7506171 [[0.5892397]
 [0.5601938]]
100 0.7096913 [[0.5027686 ]
 [0.48710346]]
200 0.7008234 [[0.34249264]
 [0.33411568]]
300 0.6966752 [[0.231335  ]
 [0.22685793]]
400 0.6947609 [[0.15605202]
 [0.15365984]]
500 0.6938837 [[0.10523036]
 [0.10395233]]
600 0.693483 [[0.07095812]
 [0.07027531]]
700 0.69330025 [[0.04785274]
 [0.04748793]]
800 0.6932169 [[0.03227522]
 [0.03208035]]
900 0.693179 [[0.02177152]
 [0.02166742]]
1000 0.69316167 [[0.01468785]
 [0.01463225]]
1100 0.69315374 [[0.00990992]
 [0.00988021]]
1200 0.69315016 [[0.00668677]
 [0.0066709 ]]
1300 0.6931485 [[0.00451221]
 [0.00450375]]
1400 0.6931478 [[0.00304499]
 [0.00304046]]
1500 0.6931474 [[0.00205493]
 [0.00205252]]
1600 0.6931473 [[0.00138685]
 [0.00138556]]
1700 0.6931473 [[0.000936  ]
 [0.00093532]]
1800 0.6931472 [[0.00063167]
 [0.00063131]]
1900 0.6931472 [[0.0004264]
 [0.0004262]]
2000 0.6931472 [[0.00028778]
 [0.00028767]]
2100 0.6931472 [[0.00019421]
 [0.00019416]]
2200 0.6931472 [[0.00013108]
 [0.00013106]]
23

위의 regressor으로는 xor 문제가 해결이 안된다. 그래서 나온 개념이 `deep learning`. layer를 늘려서 모델을 구축해보자.

xor nn(nueral network) 적용

In [6]:
tf.set_random_seed(777)

# datset
x_data=np.array([[0,0],[0,1],[1,0],[1,1]], dtype=np.float32)
y_data=np.array([[0],[1],[1],[0]], dtype=np.float32)

In [7]:
# 변수 생성
X = tf.placeholder(tf.float32, [None, 2])
Y = tf.placeholder(tf.float32, [None, 1])

##################
#### 달리진곳 ####
##################

# layer의 input 2, ouput 2
W1 = tf.Variable(tf.random_normal([2,2]), name ='weight1')
# output 과 동일하게 2로 
b1 = tf.Variable(tf.random_normal([2]), name = 'bias1') 

layer1 = tf.sigmoid(tf.matmul(X, W1) + b1)

# layer1의 output 2를 그대로 가져와서 W2 input에 넣는다. 
W2 = tf.Variable(tf.random_normal([2,1]), name ='weight1')
# weight의 output 값
b2 = tf.Variable(tf.random_normal([1]), name = 'bias1') 

##################

# 모델 구축
hypothesis = tf.sigmoid(tf.matmul(layer1, W2) + b2)

# cost/loss 함수
cost = -tf.reduce_mean(Y * tf.log(hypothesis)+(1-Y) * tf.log(1-hypothesis))
train = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

# 예측값, 정확도
predicted = tf.cast(hypothesis > 0.5, dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))

In [8]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    for step in range(10001):
        _, cost_val = sess.run([train, cost], feed_dict={X:x_data, Y:y_data})
        if step % 1000 == 0:
            print(step, cost_val)
    h, p, a = sess.run(
        [hypothesis, predicted, accuracy], feed_dict={X:x_data, Y:y_data}
    )
    print(f"\nHypothesis :\n{h} \nPredicted:\n{p} \nAccuracy:\n{a}")

0 0.6943808
1000 0.624394
2000 0.21722414
3000 0.08289158
4000 0.047588255
5000 0.03274015
6000 0.024765182
7000 0.019839302
8000 0.01651223
9000 0.014121745
10000 0.012324711

Hypothesis :
[[0.01195052]
 [0.9890093 ]
 [0.98410153]
 [0.01014063]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0


- layer를 늘리면 예상하던 대로 10000번의 시도 결과, cost는 점점 작아지고, 정확도는 높아졌다.

- 이젠 layer의 출력 값을 더 많이 늘리면 어떻게 되는지 알아보자.
    - Wide NN for XOR : output 출력을 늘리는 것. ex) W1 = tf.Variable(tf.random_normal([2,10]), name = 'weight1')
    - Deep NN for XOR : layer을 늘려가는 것. ex ) layer1, layer2, ...

In [9]:
# 변수 생성 : W, b, layer
W1 = tf.Variable(tf.random_normal([2,10]), name = 'weight1')
b1 = tf.Variable(tf.random_normal([10]), name = 'bias1')
layer1 = tf.sigmoid(tf.matmul(X,W1) + b1)

W2 = tf.Variable(tf.random_normal([10,10]), name = 'weight2')
b2 = tf.Variable(tf.random_normal([10]), name = 'bias2')
layer2 = tf.sigmoid(tf.matmul(layer1,W2) + b2)

W3 = tf.Variable(tf.random_normal([10,10]), name = 'weight3')
b3 = tf.Variable(tf.random_normal([10]), name = 'bias3')
layer3 = tf.sigmoid(tf.matmul(layer2,W3) + b3)

W4 = tf.Variable(tf.random_normal([10,1]), name = 'weight4')
b4 = tf.Variable(tf.random_normal([1]), name = 'bias4')

# 가설 
hypothesis = tf.sigmoid(tf.matmul(layer3, W4)+b4)

In [10]:
# cost/loss 함수
cost = -tf.reduce_mean(Y * tf.log(hypothesis) + (1-Y)*tf.log(1-hypothesis))
train = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

# 예측값,정확도
predicted = tf.cast(hypothesis>0.5, dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))

In [11]:
# 모델 실행
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    for step in range(10001):
        _, cost_val = sess.run([train, cost], feed_dict={X:x_data, Y:y_data})
        if step % 1000 == 0:
            print(step, cost_val)
    h, p, a = sess.run(
        [hypothesis, predicted, accuracy], feed_dict={X:x_data, Y:y_data}
    )
    print(f"\nHypothesis :\n{h} \nPredicted:\n{p} \nAccuracy:\n{a}")

0 0.9280342
1000 0.6505594
2000 0.08748222
3000 0.017788988
4000 0.008798714
5000 0.0056241574
6000 0.004053603
7000 0.0031326902
8000 0.002533981
9000 0.002116739
10000 0.0018110019

Hypothesis :
[[0.00180405]
 [0.99802315]
 [0.9980347 ]
 [0.00148997]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0


- 그결과, 작은값은 더 작아지고, 큰 값은 더 커졌다. 
- layer를 더 쌓을 수록 error가 작아진다.

## Tensor board 적용

### 5가지 스텝
1. From TF graph, decide which tensors you want to log
TF 그래프에서 어떤 tensor를 logging할지 정한다. 
```
w2_hist = tf.summary.histogram("weight2",W2)
cost_sum = tf.summary.scalar("cost", cost)
```

2. Merga all summaries
```
summary = tf.summary.merge_all()
```

3. Create writer and add graph
파일 위치를 정하여 그래프를 넣는다. 
```
writer = tf.summary.FileWriter('./logs')
writer.add_graph(sess.graph)
```

4. Run summary merge and add_summary
```
s, _ = sees.run([summary, optimizer], feed_dict=feed_dict)
writer.add_summary(s, global_step=global_step) # 실제 파일에 기록하는 부분
```

5. Launch TensorBoard
tensor 실행하면, port 6006으로 바로 확인할 수 있다.
```
tensorboard --logdir=./logs
```

remote에서 돌릴 경우엔 아래 명령어 사용하면된다.
```
ssh -L local_port:127.0.0.1:remote_port username@server.com
```

`참고`
만약 두개의 변수를 넣어 비교하고 싶다면 아래와 같이 두 결과를 같은 폴더에 그래프로 생성하면 된다. 

tensorboard -logdir =./logs/xor_logs
```
train = tf.train.GradientDescentOptimizer(learning_rate=0.1).minize(cost)
...
writer = tf.summary.FileWriter("./logs/xor_logs")
```

tensorboard -logdir =./logs/xor_logs_r0_01
```
train = tf.train.GradientDescentOptimizer(learning_rate=0.01).minize(cost)
...
writer = tf.summary.FileWriter("./logs/xor_logs_r0_01")
```



이번엔 GradientOptimizer가 아닌 AdamOptimizer 을 적용하여 비교해보자. 

In [16]:
X = tf.placeholder(tf.float32, [None, 2], name='x')
Y = tf.placeholder(tf.float32, [None, 1], name='y')

# 그래프를 그릴때 한번에 보면 복잡하기 때문에, 레이어별로 기능별로 보기 쉽게 해준다.
with tf.name_scope("Layer1"):
    W1 = tf.Variable(tf.random_normal([2,2]), name="weight_1")
    b1 = tf.Variable(tf.random_normal([2]), name="bias_1")
    layer1 = tf.sigmoid(tf.matmul(X, W1) + b1)
    # 여러개의 값을 가질 경우엔 histogram을 사용 / 하나는 scalar 사용
    tf.summary.histogram("W1", W1)
    tf.summary.histogram("b1", b1)
    tf.summary.histogram("Layer1", layer1)
    
with tf.name_scope("Layer2"):
    W2 = tf.Variable(tf.random_normal([2,1]), name="weight_2")
    b2 = tf.Variable(tf.random_normal([1]), name="bias_2")
    hypothesis = tf.sigmoid(tf.matmul(layer1, W2) + b2)
    
    tf.summary.histogram("W2", W2)
    tf.summary.histogram("b2", b2)
    tf.summary.histogram("Hypothesis", hypothesis)    
    

In [17]:
with tf.name_scope("Cost"):
    cost = -tf.reduce_mean(Y * tf.log(hypothesis) + (1-Y) * tf.log(1 - hypothesis))
    tf.summary.scalar("Cost", cost)
    
with tf.name_scope("Train"):
    train = tf.train.AdamOptimizer(learning_rate=0.01).minimize(cost)    

In [18]:
predicted = tf.cast(hypothesis > 0.5, dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))
tf.summary.scalar("accuracy", accuracy)

<tf.Tensor 'accuracy_1:0' shape=() dtype=string>

In [19]:
# 모델 실행
with tf.Session() as sess:
    # 2,3 Merge summaries and create writer after creating session
    merged_summary = tf.summary.merge_all()
    writer = tf.summary.FileWriter("./logs/xor_logs_r0_01")
    writer.add_graph(sess.graph) # show graph
    
    sess.run(tf.global_variables_initializer())
    
    for step in range(10001):
        _, cost_val = sess.run([train, cost], feed_dict={X:x_data, Y:y_data})
        if step % 1000 == 0:
            print(step, cost_val)
    h, p, a = sess.run(
        [hypothesis, predicted, accuracy], feed_dict={X:x_data, Y:y_data}
    )
    print(f"\nHypothesis :\n{h} \nPredicted:\n{p} \nAccuracy:\n{a}")

0 0.837729
1000 0.106021106
2000 0.027366921
3000 0.0117866825
4000 0.0060298624
5000 0.003340594
6000 0.0019299057
7000 0.0011414457
8000 0.0006843596
9000 0.00041367207
10000 0.00025126693

Hypothesis :
[[3.1650066e-04]
 [9.9980491e-01]
 [9.9981201e-01]
 [3.0481815e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0


이제 tensorboard를 실행하여 cost함수를 확인해보자. 
`하지만 나는 보류.. CUDA 오류`

forward prop, back prop 를 적용해보자,

In [23]:
x_data = [[1.],
          [2.],
          [3.]]

y_data = [[1.],
          [2.],
          [3.]]

X = tf.placeholder(tf.float32, shape=[None,1])
Y = tf.placeholder(tf.float32, shape=[None,1])

In [24]:
# 잘못된 weight 모델을 적용해보자. 
W = tf.Variable(tf.truncated_normal([1,1]))
b = tf.Variable(5.)

# Forward prop 구현
hypothesis = tf.matmul(X, W) + b

# diff 
assert hypothesis.shape.as_list() == Y.shape.as_list() # 모델 적용한 값과 실제 Y값을 비교함.
diff = (hypothesis- Y) # 예측값과 실제값의 차이 

In [25]:
# Back prop (chain rule)

d_l1 = diff
d_b = d_l1
d_w = tf.matmul(tf.transpose(X), d_l1)

print(X, W, d_l1, d_w)

Tensor("Placeholder_10:0", shape=(?, 1), dtype=float32) <tf.Variable 'Variable:0' shape=(1, 1) dtype=float32_ref> Tensor("sub_6:0", shape=(?, 1), dtype=float32) Tensor("MatMul_8:0", shape=(1, 1), dtype=float32)


In [31]:
# Updating network using gradients 
# gradients를 사용하여 network를 update함

learning_rate=0.1
step = [
    tf.assign(W,W-learning_rate * d_w),
    tf.assign(b,b-learning_rate * tf.reduce_mean(d_b)),
]

# cost function
RMSE = tf.reduce_mean(tf.square((Y-hypothesis)))

sess = tf.InteractiveSession()
init = tf.global_variables_initializer()
sess.run(init)

for i in range(1000):
    print(i, sess.run([step, RMSE], feed_dict={X:x_data, Y:y_data}))

print('-------------- y_pred --------------------')
print(sess.run(hypothesis, feed_dict={X:x_data}))


c:\users\hanbit\appdata\local\programs\python\python37\lib\site-packages\tensorflow\python\client\session.py:1751: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


0 [[array([[-1.4837697]], dtype=float32), 4.7581153], 6.96122]
1 [[array([[-0.86136115]], dtype=float32), 4.7790575], 4.1566]
2 [[array([[-1.12289]], dtype=float32), 4.673424], 3.425621]
3 [[array([[-0.95489824]], dtype=float32), 4.6306596], 3.1873205]
4 [[array([[-0.9964365]], dtype=float32), 4.5585732], 3.067395]
5 [[array([[-0.9365694]], dtype=float32), 4.502003], 2.9771888]
6 [[array([[-0.9265742]], dtype=float32), 4.439117], 2.895671]
7 [[array([[-0.8928405]], dtype=float32), 4.38052], 2.8178177]
8 [[array([[-0.8711757]], dtype=float32), 4.321036], 2.742397]
9 [[array([[-0.8441512]], dtype=float32), 4.2631674], 2.6690743]
10 [[array([[-0.82023996]], dtype=float32), 4.205681], 2.5977318]
11 [[array([[-0.7953125]], dtype=float32), 4.149161], 2.528301]
12 [[array([[-0.7713715]], dtype=float32), 4.0933075], 2.4607272]
13 [[array([[-0.74743587]], dtype=float32), 4.038251], 2.3949594]
14 [[array([[-0.7239762]], dtype=float32), 3.983913], 2.330949]
15 [[array([[-0.7007573]], dtype=float3

259 [[array([[0.93758696]], dtype=float32), 0.1442308], 0.0030551243]
260 [[array([[0.93842673]], dtype=float32), 0.14229032], 0.0029734669]
261 [[array([[0.9392551]], dtype=float32), 0.14037594], 0.0028939974]
262 [[array([[0.9400725]], dtype=float32), 0.13848734], 0.0028166545]
263 [[array([[0.94087857]], dtype=float32), 0.13662411], 0.002741374]
264 [[array([[0.9416741]], dtype=float32), 0.13478598], 0.002668105]
265 [[array([[0.94245887]], dtype=float32), 0.13297257], 0.0025967949]
266 [[array([[0.94323295]], dtype=float32), 0.13118355], 0.0025273869]
267 [[array([[0.94399667]], dtype=float32), 0.12941861], 0.002459835]
268 [[array([[0.9447502]], dtype=float32), 0.12767741], 0.0023940913]
269 [[array([[0.9454935]], dtype=float32), 0.12595963], 0.0023301083]
270 [[array([[0.9462268]], dtype=float32), 0.12426496], 0.0022678245]
271 [[array([[0.9469503]], dtype=float32), 0.122593105], 0.0022072205]
272 [[array([[0.947664]], dtype=float32), 0.12094373], 0.002148222]
273 [[array([[0.948

566 [[array([[0.9990244]], dtype=float32), 0.0022546907], 7.465778e-07]
567 [[array([[0.9990374]], dtype=float32), 0.00222434], 7.266581e-07]
568 [[array([[0.9990504]], dtype=float32), 0.0021944186], 7.0712855e-07]
569 [[array([[0.9990632]], dtype=float32), 0.0021649024], 6.8830764e-07]
570 [[array([[0.99907583]], dtype=float32), 0.0021357755], 6.6998206e-07]
571 [[array([[0.9990882]], dtype=float32), 0.0021070302], 6.5209633e-07]
572 [[array([[0.99910045]], dtype=float32), 0.0020786782], 6.346024e-07]
573 [[array([[0.99911255]], dtype=float32), 0.0020507157], 6.175829e-07]
574 [[array([[0.9991246]], dtype=float32), 0.0020231386], 6.0116923e-07]
575 [[array([[0.99913627]], dtype=float32), 0.0019959032], 5.850059e-07]
576 [[array([[0.99914795]], dtype=float32), 0.0019690613], 5.694031e-07]
577 [[array([[0.9991594]], dtype=float32), 0.0019425651], 5.5412835e-07]
578 [[array([[0.99917066]], dtype=float32), 0.0019164265], 5.3933303e-07]
579 [[array([[0.9991819]], dtype=float32), 0.00189065

867 [[array([[0.99998355]], dtype=float32), 3.8232443e-05], 2.1609974e-10]
868 [[array([[0.99998367]], dtype=float32), 3.770395e-05], 2.0966222e-10]
869 [[array([[0.99998397]], dtype=float32), 3.7207246e-05], 2.0378839e-10]
870 [[array([[0.9999841]], dtype=float32), 3.669067e-05], 1.9934987e-10]
871 [[array([[0.9999843]], dtype=float32), 3.6205885e-05], 1.9108863e-10]
872 [[array([[0.99998456]], dtype=float32), 3.57211e-05], 1.8608641e-10]
873 [[array([[0.99998474]], dtype=float32), 3.5236313e-05], 1.8115998e-10]
874 [[array([[0.9999849]], dtype=float32), 3.4759476e-05], 1.779578e-10]
875 [[array([[0.9999852]], dtype=float32), 3.4302506e-05], 1.7248662e-10]
876 [[array([[0.99998534]], dtype=float32), 3.382567e-05], 1.684081e-10]
877 [[array([[0.9999855]], dtype=float32), 3.33687e-05], 1.6305061e-10]
878 [[array([[0.99998575]], dtype=float32), 3.29316e-05], 1.5781627e-10]
879 [[array([[0.99998593]], dtype=float32), 3.2482578e-05], 1.5545254e-10]
880 [[array([[0.9999862]], dtype=float32)

Multi linear back prop 적용

In [32]:
# tf Graph Input
x_data = [[73., 80., 75.],
          [93., 88., 93.],
          [89., 91., 90.],
          [96., 98., 100.],
          [73., 66., 70.]]
y_data = [[152.],
          [185.],
          [180.],
          [196.],
          [142.]]

# 변수 선언
X = tf.placeholder(tf.float32, shape=[None,3])
Y = tf.placeholder(tf.float32, shape=[None,1])

# 잘못된 weights 적용
W = tf.Variable(tf.truncated_normal([3,1]))
b = tf.Variable(5.)

# Forward prop
hypothesis = tf.matmul(X,W) + b

print(hypothesis.shape, Y.shape) # 아직은 X에 얼마나 들어올지 모르니 `?`

(?, 1) (?, 1)


In [33]:
# diff
assert hypothesis.shape.as_list() == Y.shape.as_list()
diff = (hypothesis - Y)

# Back prop (chain rule)
d_l1 = diff
d_b = d_l1
d_w = tf.matmul(tf.transpose(X), d_l1)

print(X, d_l1, d_w )

Tensor("Placeholder_12:0", shape=(?, 3), dtype=float32) Tensor("sub_16:0", shape=(?, 1), dtype=float32) Tensor("MatMul_10:0", shape=(3, 1), dtype=float32)


In [37]:
# updating network using gradients
learning_rate = 1e-6
step = [
    tf.assign(W, W-learning_rate * d_w),
    tf.assign(b,b-learning_rate * tf.reduce_mean(d_b))
]

RMSE = tf.reduce_mean(tf.square((Y- hypothesis)))

sess = tf.InteractiveSession()
init = tf.global_variables_initializer()

sess.run(init)

for i in range(10000):
    if i%100 == 0 : 
        print(i, sess.run([step, RMSE], feed_dict={X:x_data, Y:y_data}))

print(sess.run(hypothesis, feed_dict={X:x_data}))

c:\users\hanbit\appdata\local\programs\python\python37\lib\site-packages\tensorflow\python\client\session.py:1751: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


0 [[array([[ 1.0084703 ],
       [-0.37644458],
       [-0.49314386]], dtype=float32), 5.0001736], 30677.062]
100 [[array([[ 1.0749533 ],
       [-0.30997485],
       [-0.42586267]], dtype=float32), 5.000328], 24298.742]
200 [[array([[ 1.1341183 ],
       [-0.25081584],
       [-0.36598456]], dtype=float32), 5.0004654], 19246.816]
300 [[array([[ 1.1867706 ],
       [-0.19816314],
       [-0.312695  ]], dtype=float32), 5.000588], 15245.463]
400 [[array([[ 1.2336266 ],
       [-0.15130085],
       [-0.265269  ]], dtype=float32), 5.0006967], 12076.203]
500 [[array([[ 1.2753242 ],
       [-0.10959185],
       [-0.22306144]], dtype=float32), 5.0007935], 9566.004]
600 [[array([[ 1.312431  ],
       [-0.07246912],
       [-0.18549812]], dtype=float32), 5.00088], 7577.8096]
700 [[array([[ 1.3454521 ],
       [-0.03942804],
       [-0.15206802]], dtype=float32), 5.0009565], 6003.067]
800 [[array([[ 1.3748369 ],
       [-0.01001951],
       [-0.12231636]], dtype=float32), 5.0010247], 4755.7983]


7500 [[array([[1.6108967 ],
       [0.22934243],
       [0.11816287]], dtype=float32), 5.0015683], 5.217664]
7600 [[array([[1.6108816 ],
       [0.22937997],
       [0.11817249]], dtype=float32), 5.0015683], 5.216939]
7700 [[array([[1.6108652 ],
       [0.22941634],
       [0.11818093]], dtype=float32), 5.0015683], 5.216292]
7800 [[array([[1.6108478 ],
       [0.22945167],
       [0.11818831]], dtype=float32), 5.0015683], 5.215583]
7900 [[array([[1.6108296 ],
       [0.22948608],
       [0.11819477]], dtype=float32), 5.0015683], 5.2149696]
8000 [[array([[1.6108105 ],
       [0.22951965],
       [0.11820038]], dtype=float32), 5.0015683], 5.214365]
8100 [[array([[1.6107907 ],
       [0.22955249],
       [0.11820526]], dtype=float32), 5.0015683], 5.2137413]
8200 [[array([[1.6107702 ],
       [0.22958468],
       [0.11820948]], dtype=float32), 5.0015683], 5.2131586]
8300 [[array([[1.6107491 ],
       [0.22961628],
       [0.11821311]], dtype=float32), 5.0015683], 5.212554]
8400 [[array([[1

가면 갈 수록 cost가 작아진다.

## zoo 예제로 NN 적용

In [88]:
xy= np.loadtxt('/Data-Science/alldeaplearning/data/data-04-zoo.csv', 
              delimiter=',', dtype=np.float32)
X_data = xy[:, 0:-1]
N = X_data.shape[0]
y_data = xy[:,[-1]]

print("y has one of the following values")
print(np.unique(y_data)) # 0~6으로 구성

y has one of the following values
[0. 1. 2. 3. 4. 5. 6.]


In [89]:
# X_data.shape = (101, 16) => 101 samples, 16 features
# y_data.shape = (101, 1)  => 101 samples, 1 label

print("Shape of X data:", X_data.shape)
print("Shape of y data:", y_data.shape)

Shape of X data: (101, 16)
Shape of y data: (101, 1)


In [90]:
nb_classes = 7 # 0~6

X = tf.placeholder(tf.float32, [None, 16])
y = tf.placeholder(tf.int32, [None, 1]) # 0~6

target = tf.one_hot(y, nb_classes) # float32는 error 발생. int 형만 가능.
target = tf.reshape(target, [-1, nb_classes])
target = tf.cast(target, tf.float32)

In [91]:
# W, b 설정
W = tf.Variable(tf.random_normal([16, nb_classes]), name = 'weight')
b = tf.Variable(tf.random_normal([nb_classes]), name = 'bias')

In [92]:
#sigmoid function 설정
def sigma(x):
    return 1./ (1. + tf.exp(-x))

def sigma_prime(x):
    return sigma(x) * (1. - sigma(x))

# 앞에서부터 값을 넣어보자! -> Forward propation
layer_1 = tf.matmul(X, W) + b
y_pred = sigma(layer_1)

# Loss Function (end of forward propagtion)
loss_i = - target * tf.log(y_pred) - (1. - target) * tf.log(1. - y_pred)
loss = tf.reduce_sum(loss_i)


In [93]:
# Dimension Chekck
assert y_pred.shape.as_list() == target.shape.as_list()

In [94]:
# Back prop (chain rule)
d_loss = (y_pred - target) / (y_pred * (1. - y_pred) + 1e-7)
d_sigma = sigma_prime(layer_1)
d_layer = d_loss * d_sigma
d_b = d_layer
d_W = tf.matmul(tf.transpose(X), d_layer)

In [95]:
# Updating network using gradient
learning_rater = 0.01
train_step = [
    tf.assign(W, W - learning_rate * d_W),
    tf.assign(b, b - learning_rate * tf.reduce_sum(d_b)),
]

In [96]:
# Prediction and Accuracy
prediction = tf.argmax(y_pred, 1)
acct_mat = tf.equal(tf.argmax(y_pred, 1), tf.argmax(target, 1))
acct_res = tf.reduce_mean(tf.cast(acct_mat, tf.float32))

In [97]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    for step in range(500):
        sess.run(train_step, feed_dict={X:X_data, y:y_data })
        
        if step % 10 == 0:
            # 아마 300 step 내에서 정확도가 100%로 가는 것을 볼 수 있다. 
            step_loss, acc = sess.run([loss, acct_res], 
                                      feed_dict={X:X_data, y:y_data})
            print("Step : {:5} \t Loss: {:10.5f}\t Acc: {:.2%}".format(
            step, step_loss, acc))
            
    # 자이제 예측 해보자.
    pred  = sess.run(prediction, feed_dict={X: X_data})
    for p, y in zip(pred, y_data):
        msg = "[{}]\t Prediction: {:d}\t True y: {:d}"
        print(msg.format(p == int(y[0]), p, int(y[0])))

Step :     0 	 Loss: 1659.00952	 Acc: 9.90%
Step :    10 	 Loss: 1654.85840	 Acc: 9.90%
Step :    20 	 Loss: 1650.87744	 Acc: 9.90%
Step :    30 	 Loss: 1646.85059	 Acc: 9.90%
Step :    40 	 Loss: 1642.91919	 Acc: 9.90%
Step :    50 	 Loss: 1638.91699	 Acc: 9.90%
Step :    60 	 Loss: 1634.85352	 Acc: 9.90%
Step :    70 	 Loss: 1630.18726	 Acc: 9.90%
Step :    80 	 Loss: 1626.21423	 Acc: 9.90%
Step :    90 	 Loss: 1622.26855	 Acc: 9.90%
Step :   100 	 Loss: 1618.31262	 Acc: 9.90%
Step :   110 	 Loss: 1614.32556	 Acc: 9.90%
Step :   120 	 Loss: 1610.40002	 Acc: 9.90%
Step :   130 	 Loss: 1606.48718	 Acc: 9.90%
Step :   140 	 Loss: 1602.58545	 Acc: 9.90%
Step :   150 	 Loss: 1598.60278	 Acc: 9.90%
Step :   160 	 Loss: 1594.73804	 Acc: 9.90%
Step :   170 	 Loss: 1590.82092	 Acc: 9.90%
Step :   180 	 Loss: 1586.97705	 Acc: 9.90%
Step :   190 	 Loss: 1583.04480	 Acc: 9.90%
Step :   200 	 Loss: 1579.20642	 Acc: 9.90%
Step :   210 	 Loss: 1575.38562	 Acc: 9.90%
Step :   220 	 Loss: 1571.54565	

정확도가 안나오네. 왜지?

# Lab 9 XOR-back_prop

back progation 구현

In [ ]:
learning_rate = 0.1

x_data = [[0,0],
          [0,1],
          [1,0],
          [1,1]]

y_data = [[0],
          [1],
          [1],
          [0]]

x_data = np.array(x_data, dtype=np.float32)
y_data = np.array(y_data, dtype=np.float32)

# 변수 생성 
X= tf.placeholder(tf.float32, [None,2])
Y= tf.placeholder(tf.float32, [None,1])

W1 = tf.Variable(tf.random_normal([2,2]), name='weight1')
b1 = tf.Variable(tf.random_normal([2]), name='bias1')
l1 = tf.sigmoid(tf.matmul(X, W1) + b1)

W2 = tf.Variable(tf.random_normal([2,1]), name='weight2')
b2 = tf.Variable(tf.random_normal([1]), name = 'bias2')
Y_pred = tf.sigmoid(tf.matmul(l1, W2) + b2)

# Cost/loss Funtion
cost = -tf.reduce_mean(Y * tf.log(Y_pred) + (1-Y) * tf.log(1-Y_pred))

# Loss derivative
d_Y_pred = (Y_pred - Y) / (Y_pred * (1.0 - Y_pred) + 1e-7)

# Layer2
d_sigma2 = Y_pred * (1-Y_pred)

d_a2 = d_Y_pred * d_sigma2
d_p2 = d_a2
d_b2 = d_a2
d_W2 = tf.matmul(tf.transpose(l1), d_p2)
