In [7]:
import tensorflow.compat.v1 as tf 
tf.disable_v2_behavior()
import numpy as np

Instructions for updating:
non-resource variables are not supported in the long term


In [8]:
tf.set_random_seed(777)

x_data=np.array([[0,0],[0,1],[1,0],[1,1]], dtype=np.float32)
y_data=np.array([[0],[1],[1],[0]], dtype=np.float32)

In [9]:
# 변수 선언
X = tf.placeholder(tf.float32, [None,2]) # x1, x2 
Y = tf.placeholder(tf.float32, [None,1]) # y
W = tf.Variable(tf.random_normal([2,1]), name ="weight") # x변수 2개, y변수 1개
b = tf.Variable(tf.random_normal([1]), name = "bias")

In [11]:
# logistic regression
hypothesis = tf.sigmoid(tf.matmul(X,W) + b)

# cost/loss function
cost = -tf.reduce_mean( Y * tf.log(hypothesis) + (1-Y)*tf.log(1-hypothesis))
train = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

# Accuracy computation 
# 만약 hypotesis 결과가 0.5 이상이면 False
predicted = tf.cast(hypothesis > 0.5, dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))

In [12]:
# 그래프 실행
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    for step in range(10001):
        _, cost_val, w_val = sess.run(
            [train, cost, W] , feed_dict={X:x_data, Y:y_data}
        )
        if step % 100 == 0:
            print(step, cost_val, w_val)
            
    h, c, a = sess.run(
        [hypothesis, predicted, accuracy], feed_dict={X:x_data, Y: y_data}
    )
    
    print("\nHypotesis: ", h, "\nCorrect: ", c, "\nAccuracy: ", a )

0 0.7506171 [[0.5892397]
 [0.5601938]]
100 0.7096913 [[0.5027686 ]
 [0.48710346]]
200 0.7008234 [[0.34249264]
 [0.33411568]]
300 0.6966752 [[0.231335  ]
 [0.22685793]]
400 0.6947609 [[0.15605202]
 [0.15365984]]
500 0.6938837 [[0.10523036]
 [0.10395233]]
600 0.693483 [[0.07095812]
 [0.07027531]]
700 0.69330025 [[0.04785274]
 [0.04748793]]
800 0.6932169 [[0.03227522]
 [0.03208035]]
900 0.693179 [[0.02177152]
 [0.02166742]]
1000 0.69316167 [[0.01468785]
 [0.01463225]]
1100 0.69315374 [[0.00990992]
 [0.00988021]]
1200 0.69315016 [[0.00668677]
 [0.0066709 ]]
1300 0.6931485 [[0.00451221]
 [0.00450375]]
1400 0.6931478 [[0.00304499]
 [0.00304046]]
1500 0.6931474 [[0.00205493]
 [0.00205252]]
1600 0.6931473 [[0.00138685]
 [0.00138556]]
1700 0.6931473 [[0.000936  ]
 [0.00093532]]
1800 0.6931472 [[0.00063167]
 [0.00063131]]
1900 0.6931472 [[0.0004264]
 [0.0004262]]
2000 0.6931472 [[0.00028778]
 [0.00028767]]
2100 0.6931472 [[0.00019421]
 [0.00019416]]
2200 0.6931472 [[0.00013108]
 [0.00013106]]
23

위의 regressor으로는 xor 문제가 해결이 안된다. 그래서 나온 개념이 `deep learning`. layer를 늘려서 모델을 구축해보자.

xor nn(nueral network) 적용

In [ ]:
tf.set_random_seed(777)

# datset
x_data=np.array([[0,0],[0,1],[1,0],[1,1]], dtype=np.float32)
y_data=np.array([[0],[1],[1],[0]], dtype=np.float32)

In [13]:
# 변수 생성
X = tf.placeholder(tf.float32, [None, 2])
Y = tf.placeholder(tf.float32, [None, 1])

W1 = tf.Variable(tf.random_normal([2,2]), name ='weight1')
b1 = tf.Variable(tf.random_normal([2]), name = 'bias1') #? b1왜 2?

layer1 = tf.sigmoid(tf.matmul(X, W1) + b1)

W2 = tf.Variable(tf.random_normal([2,1]), name ='weight1')
b2 = tf.Variable(tf.random_normal([1]), name = 'bias1') #? b1왜 2?

# 모델 구축
hypothesis = tf.sigmoid(tf.matmul(layer1, W2) + b2)

# cost/loss 함수
cost = -tf.reduce_mean(Y * tf.log(hypothesis)+(1-Y) * tf.log(1-hypothesis))
train = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

# 예측값, 정확도
predicted = tf.cast(hypothesis > 0.5, dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))

In [18]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    for step in range(10001):
        _, cost_val = sess.run([train, cost], feed_dict={X:x_data, Y:y_data})
        if step % 1000 == 0:
            print(step, cost_val)
    h, p, a = sess.run(
        [hypothesis, predicted, accuracy], feed_dict={X:x_data, Y:y_data}
    )
    print(f"\nHypothesis :\n{h} \nPredicted:\n{p} \nAccuracy:\n{a}")

0 0.6943808
1000 0.624394
2000 0.21722414
3000 0.08289158
4000 0.047588255
5000 0.03274015
6000 0.024765182
7000 0.019839302
8000 0.01651223
9000 0.014121745
10000 0.012324711

Hypothesis :
[[0.01195052]
 [0.9890093 ]
 [0.98410153]
 [0.01014063]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0


- layer를 늘리면 예상하던 대로 10000번의 시도 결과, cost는 점점 작아지고, 정확도는 높아졌다.

- 이젠 layer를 더 많이 늘리면 어떻게 되는지 알아보자.

In [21]:
# 변수 생성 : W, b, layer
W1 = tf.Variable(tf.random_normal([2,10]), name = 'weight1')
b1 = tf.Variable(tf.random_normal([10]), name = 'bias1')
layer1 = tf.sigmoid(tf.matmul(X,W1) + b1)

W2 = tf.Variable(tf.random_normal([10,10]), name = 'weight2')
b2 = tf.Variable(tf.random_normal([10]), name = 'bias2')
layer2 = tf.sigmoid(tf.matmul(layer1,W2) + b2)

W3 = tf.Variable(tf.random_normal([10,10]), name = 'weight3')
b3 = tf.Variable(tf.random_normal([10]), name = 'bias3')
layer3 = tf.sigmoid(tf.matmul(layer2,W3) + b3)

W4 = tf.Variable(tf.random_normal([10,1]), name = 'weight4')
b4 = tf.Variable(tf.random_normal([1]), name = 'bias4')

# 가설 
hypothesis = tf.sigmoid(tf.matmul(layer3, W4)+b4)

In [23]:
# cost/loss 함수
cost = -tf.reduce_mean(Y * tf.log(hypothesis) + (1-Y)*tf.log(1-hypothesis))
train = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

# 예측값,정확도
predicted = tf.cast(hypothesis>0.5, dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))

In [24]:
# 모델 실행
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    for step in range(10001):
        _, cost_val = sess.run([train, cost], feed_dict={X:x_data, Y:y_data})
        if step % 1000 == 0:
            print(step, cost_val)
    h, p, a = sess.run(
        [hypothesis, predicted, accuracy], feed_dict={X:x_data, Y:y_data}
    )
    print(f"\nHypothesis :\n{h} \nPredicted:\n{p} \nAccuracy:\n{a}")

0 1.1099052
1000 0.53118896
2000 0.046242997
3000 0.014703564
4000 0.008102539
5000 0.005451985
6000 0.004057234
7000 0.0032070503
8000 0.0026386217
9000 0.002233629
10000 0.001931418

Hypothesis :
[[0.00204578]
 [0.99882996]
 [0.99703944]
 [0.0015398 ]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0


- layer를 더 쌓을 수록 error가 작아진다.

In [26]:
X = tf.placeholder(tf.float32, [None, 2], name='x')
Y = tf.placeholder(tf.float32, [None, 1], name='y')

with tf.name_scope("Layer1"):
    W1 = tf.Variable(tf.random_normal([2,2]), name="weight_1")
    b1 = tf.Variable(tf.random_normal([2]), name="bias_1")
    layer1 = tf.sigmoid(tf.matmul(X, W1) + b1)
    
    tf.summary.histogram("W1", W1)
    tf.summary.histogram("b1", b1)
    tf.summary.histogram("Layer1", layer1)
    
with tf.name_scope("Layer2"):
    W2 = tf.Variable(tf.random_normal([2,1]), name="weight_2")
    b2 = tf.Variable(tf.random_normal([1]), name="bias_2")
    layer1 = tf.sigmoid(tf.matmul(layer1, W2) + b2)
    
    tf.summary.histogram("W2", W2)
    tf.summary.histogram("b2", b2)
    tf.summary.histogram("Hypothesis", hypothesis)    
    

In [29]:
with tf.name_scope("Cost"):
    cost = -tf.reduce_mean(Y * tf.log(hypothesis) + (1-Y) * tf.log(1 - hypothesis))
    tf.summary.scalar("Cost", cost)
    
with tf.name_scope("Train"):
    train = tf.train.AdamOptimizer(learning_rate=0.01).minimize(cost)    

In [30]:
predicted = tf.cast(hypothesis > 0.5, dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))
tf.summary.scalar("accuracy", accuracy)

<tf.Tensor 'accuracy:0' shape=() dtype=string>

In [31]:
# 모델 실행
with tf.Session() as sess:
    
    merged_summary = tf.summary.merge_all()
    writer = tf.summary.FileWriter("./logs/xor_logs_r0_01")
    writer.add_graph(sess.graph)    
    
    sess.run(tf.global_variables_initializer())
    
    for step in range(10001):
        _, cost_val = sess.run([train, cost], feed_dict={X:x_data, Y:y_data})
        if step % 1000 == 0:
            print(step, cost_val)
    h, p, a = sess.run(
        [hypothesis, predicted, accuracy], feed_dict={X:x_data, Y:y_data}
    )
    print(f"\nHypothesis :\n{h} \nPredicted:\n{p} \nAccuracy:\n{a}")

InvalidArgumentError: You must feed a value for placeholder tensor 'Placeholder_2' with dtype float and shape [?,2]
	 [[node Placeholder_2 (defined at <ipython-input-13-2a045ce50dee>:2) ]]

Original stack trace for 'Placeholder_2':
  File "D:\AnacondaDev\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\AnacondaDev\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\AnacondaDev\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "D:\AnacondaDev\lib\site-packages\traitlets\config\application.py", line 664, in launch_instance
    app.start()
  File "D:\AnacondaDev\lib\site-packages\ipykernel\kernelapp.py", line 612, in start
    self.io_loop.start()
  File "D:\AnacondaDev\lib\site-packages\tornado\platform\asyncio.py", line 149, in start
    self.asyncio_loop.run_forever()
  File "D:\AnacondaDev\lib\asyncio\base_events.py", line 541, in run_forever
    self._run_once()
  File "D:\AnacondaDev\lib\asyncio\base_events.py", line 1786, in _run_once
    handle._run()
  File "D:\AnacondaDev\lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "D:\AnacondaDev\lib\site-packages\tornado\ioloop.py", line 690, in <lambda>
    lambda f: self._run_callback(functools.partial(callback, future))
  File "D:\AnacondaDev\lib\site-packages\tornado\ioloop.py", line 743, in _run_callback
    ret = callback()
  File "D:\AnacondaDev\lib\site-packages\tornado\gen.py", line 787, in inner
    self.run()
  File "D:\AnacondaDev\lib\site-packages\tornado\gen.py", line 748, in run
    yielded = self.gen.send(value)
  File "D:\AnacondaDev\lib\site-packages\ipykernel\kernelbase.py", line 365, in process_one
    yield gen.maybe_future(dispatch(*args))
  File "D:\AnacondaDev\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "D:\AnacondaDev\lib\site-packages\ipykernel\kernelbase.py", line 268, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "D:\AnacondaDev\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "D:\AnacondaDev\lib\site-packages\ipykernel\kernelbase.py", line 545, in execute_request
    user_expressions, allow_stdin,
  File "D:\AnacondaDev\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "D:\AnacondaDev\lib\site-packages\ipykernel\ipkernel.py", line 306, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "D:\AnacondaDev\lib\site-packages\ipykernel\zmqshell.py", line 536, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "D:\AnacondaDev\lib\site-packages\IPython\core\interactiveshell.py", line 2877, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "D:\AnacondaDev\lib\site-packages\IPython\core\interactiveshell.py", line 2922, in _run_cell
    return runner(coro)
  File "D:\AnacondaDev\lib\site-packages\IPython\core\async_helpers.py", line 68, in _pseudo_sync_runner
    coro.send(None)
  File "D:\AnacondaDev\lib\site-packages\IPython\core\interactiveshell.py", line 3146, in run_cell_async
    interactivity=interactivity, compiler=compiler, result=result)
  File "D:\AnacondaDev\lib\site-packages\IPython\core\interactiveshell.py", line 3337, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "D:\AnacondaDev\lib\site-packages\IPython\core\interactiveshell.py", line 3417, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-13-2a045ce50dee>", line 2, in <module>
    X = tf.placeholder(tf.float32, [None, 2])
  File "D:\AnacondaDev\lib\site-packages\tensorflow\python\ops\array_ops.py", line 3100, in placeholder
    return gen_array_ops.placeholder(dtype=dtype, shape=shape, name=name)
  File "D:\AnacondaDev\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 6809, in placeholder
    "Placeholder", dtype=dtype, shape=shape, name=name)
  File "D:\AnacondaDev\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 744, in _apply_op_helper
    attrs=attr_protos, op_def=op_def)
  File "D:\AnacondaDev\lib\site-packages\tensorflow\python\framework\ops.py", line 3485, in _create_op_internal
    op_def=op_def)
  File "D:\AnacondaDev\lib\site-packages\tensorflow\python\framework\ops.py", line 1949, in __init__
    self._traceback = tf_stack.extract_stack()
